export const meta = {
  name: 'cmake-wave1-ground-and-scout',
  description: 'CMake + C++ package-management research program wave 1: four grounding audits (find_ocx, fleet + Bazel overlap, two exemplar-corpus censuses) and five landscape scouts',
  phases: [
    { title: 'Ground', detail: 'numbers-first audits of find_ocx, the fleet, and a 46-repo exemplar corpus' },
    { title: 'Scout', detail: 'five corpus surveys that discover candidate topics' },
  ],
}

const ROOT = '/home/mherwig/dev/grimoire-lore/.agents/worktrees/java'
const RESEARCH = ROOT + '/.agents/research'
const FRAME = RESEARCH + '/cmake-frame.md'
const BAZEL_RESEARCH = '/home/mherwig/dev/grimoire-lore/.agents/research'
const EXEMPLARS = '/tmp/claude-1000/-home-mherwig-dev-grimoire-lore--agents-worktrees-java/c4f22277-6831-442c-8bc3-1be41a79fdff/scratchpad/exemplars'
const EXEMPLAR_TABLE = RESEARCH + '/cmake-audit/scratch/exemplar-table.md'
const DATE = '2026-09-05'

const PREAMBLE = (rationale) => 'Model rationale: sonnet — ' + rationale + `

PROJECT CONTEXT (context for you, not content to reproduce):
- This is the research program that makes an AI-agent fleet expert in CMake and in C++ package management (Conan 2, vcpkg, Hunter and its cpp-pm fork, CPM.cmake, dependency providers) including the CMake side of Bazel interoperability. Its output becomes AI-agent configuration (rules and possibly skills) used without a human in the loop, published through the lore catalog at ` + ROOT + `.
- Read the frame first, in full: ` + FRAME + `. It names the era (CMake 4.x current, 3.19 floor in the one fleet consumer, September 2026), the adopting codebases, the requester's hypotheses, the companion contract with the Bazel program, and the artifact set.
- The fleet under /home/mherwig/dev has ONE CMake codebase and ZERO C++ codebases. /home/mherwig/dev/find_ocx is CMake support for the OCX package manager: two copy-and-own files (ocx.cmake, 1,506 lines; Findocx.cmake, 90 lines) that bootstrap a pinned sha256-verified ocx CLI and provision tools through it. Its working tree is DIRTY (an in-flight ocx 0.5.2 adoption; see its OCX-0.5-HANDOVER.md). Because the fleet has no C++, grounding for the C++ side runs against an exemplar corpus of upstream repositories cloned blob-less into ` + EXEMPLARS + ` (one directory per repo, named owner__repo; build and config files checked out, source blobs fetchable with git show HEAD:path).
- This program is a COMPANION to the Bazel research program whose corpus lives read-only at ` + BAZEL_RESEARCH + ` (bazel-frame.md, bazel-topic-map.md, bazel-topic-map/*.md, bazel-audit/*.md). Its group 9 (family BZL-CC) owns rules_cc, hermetic C++ toolchains, layering_check, sanitizers under Bazel, compile_commands under Bazel, C++20 modules under Bazel, and rules_foreign_cc from the Bazel side. Do not re-derive those; mark them covered-elsewhere and cite the row (M-L-nn). This program owns the CMake side of the seam.
- Sibling lore rule sets already exist for Rust (rust-quality, rust-cargo), Python (python-quality, python-packaging), TypeScript (typescript-quality, typescript-packaging), CSS and docs, under ` + ROOT + `/rules. A topic that is really a Cargo, pyproject or package.json topic belongs to those sets.
- The requester's diagnosis (frame section "The requester's hypothesis") is a HYPOTHESIS to test, never a premise. Contradicting it with evidence is the most valuable result you can produce.
- Do not read under any .agents/worktrees/, target/, node_modules/, build/, docs/.venv/, .git/ directory (the exemplar corpus directories are the exception: read their checked-out files and use git ls-tree / git show inside them). Use read-only tools on every repository; never run a build, cmake configure, conan or vcpkg command inside any repository; the only file you may create or modify is your own OUTPUT FILE (and, for exemplar audits, measurement scripts and TSVs under ` + RESEARCH + `/cmake-audit/scratch/).
- Date everything you write as researched ` + DATE + `. Flag anything CMake-minor-, Conan-, vcpkg- or Bazel-version-specific with the version it applies to.

ALREADY COVERED: nothing — this is the first wave of the CMake program. Adjacent coverage: the Bazel program's C++ group (BZL-CC) and the sibling Rust/Python/TypeScript sets named above.
`

const GROUND_CONTRACT = (codebase, path) => 'You are producing a numbers-first audit of ' + codebase + ` so a later authoring pass is grounded in what is actually there.

Write ` + path + ` with YAML frontmatter (title, agent, model, scope, method, date_researched: ` + DATE + `). The method field must describe the exact commands used so every number is re-runnable; inline each command next to its result.

The requester's diagnosis of this codebase is a HYPOTHESIS, not a premise. If the measurements contradict it, say so plainly and show the counts. That is the most valuable result this audit can produce.

Every claim needs a file:line citation (for exemplars: repo@sha:path:line, where sha is the short HEAD of that clone). Where docs and code disagree, say which one is authoritative in practice.

Structure: frontmatter, a table of contents, "## Headline numbers", one "## <axis>" section per numbered demand below (each with commands inline), "## Smells (ranked)", "## Patterns worth encoding", "## Contradictions of the frame", "## Gaps". Aim for 300-600 lines; density over prose. Tables over paragraphs.

Use read-only tools. Do not modify anything outside your output file (and your scratch scripts, where the demands say so). Return max 35 lines as the structured receipt.`

const SCOUT_CONTRACT = (corpusName, path) => `You are a LANDSCAPE SCOUT. Your job is NOT to answer questions — it is to DISCOVER which questions exist. Survey a corpus and come back with the topics an expert must be expert in, ranked by how much each changes real code quality.

YOUR CORPUS: ` + corpusName + `

OUTPUT FILE: ` + path + `

Structure, in this order:
1. YAML frontmatter: title, corpus, agent, model, date_researched: ` + DATE + `, sources_count, scope (2-3 lines on what is and is not covered).
2. A table of contents.
3. "## Summary" — 10-20 bullet lines, each a standalone claim about what this corpus says matters.
4. "## Survey" — numbered subsections, one per source or source cluster actually read: what it argues or lists, with an inline markdown link to the exact URL read. Quote exact command names, variable names, policy numbers, lint codes, flag names, version numbers, numeric thresholds.
5. "## Candidate topics" — a table: topic (a QUESTION, not a subject area) | why it matters | source (URL) | already-covered? (yes/partial/no, against the frame's existing config, the Bazel program's BZL-CC group and the sibling lore sets) | priority for THIS project shape (P0-P3, one clause of justification). Aim for 25-45 candidates. Be exhaustive and specific. Include the topics that sound boring but bite: version floors, policy defaults, quoting and list semantics, scoping, cache-variable stickiness, configure-time versus build-time, generator differences, path handling on Windows, RPATH, ABI and standard mismatches, lockfile and baseline formats, binary-cache keys, reproducibility, deprecations.
6. "## Recent shifts seen in this corpus" — what changed in the last 18-24 months and what older advice it invalidates, with the version and date.
7. "## Contested" — where sources disagree, and which way it is trending.
8. "## Sources" — table: URL | what it is | date/era | why worth reading. Minimum 15 distinct sources, at least 8 primary (official docs, the tool's own repository, release notes, talk recordings or slides, papers, surveys with methodology).

Hard requirements:
- Load the web tools first: call ToolSearch with query "select:WebSearch,WebFetch" before anything else. For GitHub-hosted markdown (README, docs/, CHANGELOG, release notes) prefer fetching the raw file verbatim with curl -sL https://raw.githubusercontent.com/<org>/<repo>/<branch>/<path> through Bash, because WebFetch returns a summary and a catalogue sweep needs the full list. For CMake documentation, the raw reStructuredText sources under https://gitlab.kitware.com/cmake/cmake/-/raw/master/Help/ are verbatim and complete. Use gh api for GitHub issue and PR lists where it helps (read-only).
- Actually FETCH the primary sources; never write from search snippets.
- Reflect current practice as of ` + DATE + `; flag historical-only guidance. Where a source predates CMake 4.0, say whether its advice survives the 4.0 compatibility-floor removal.
- A candidate is a question a rule could later answer with a verification command. "Modern CMake" is a wave; "when does a FetchContent dependency silently shadow the system copy find_package would have found, and how is it detected" is a topic.
- Do not modify any file other than your output file. Return max 45 lines as the structured receipt, with the candidate list as structured data.`

const GROUND_SCHEMA = {
  type: 'object',
  properties: {
    path: { type: 'string' },
    headline_numbers: { type: 'array', items: { type: 'string' } },
    top_smells: { type: 'array', items: { type: 'string' } },
    patterns_worth_encoding: { type: 'array', items: { type: 'string' } },
    contradictions_of_frame: { type: 'array', items: { type: 'string' } },
  },
  required: ['path', 'headline_numbers', 'top_smells', 'patterns_worth_encoding', 'contradictions_of_frame'],
}

const SCOUT_SCHEMA = {
  type: 'object',
  properties: {
    path: { type: 'string' },
    sources_count: { type: 'number' },
    primary_sources_count: { type: 'number' },
    candidates: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          slug: { type: 'string' },
          why: { type: 'string' },
          source: { type: 'string' },
          covered: { type: 'string', enum: ['yes', 'partial', 'no'] },
          priority: { type: 'string', enum: ['P0', 'P1', 'P2', 'P3'] },
        },
        required: ['slug', 'why', 'source', 'covered', 'priority'],
      },
    },
    recent_shifts: { type: 'array', items: { type: 'string' } },
  },
  required: ['path', 'sources_count', 'primary_sources_count', 'candidates', 'recent_shifts'],
}

// ---------------------------------------------------------------- Ground
const GROUNDERS = [
  {
    key: 'find-ocx-cmake-shape-and-contracts',
    prompt: PREAMBLE('counting and measuring a 1,600-line CMake module and diffing its documented contracts against code; volume work with commands, no rule decisions') + '\n' +
      GROUND_CONTRACT('/home/mherwig/dev/find_ocx (CMake code shape, implemented contracts, runtime posture)', RESEARCH + '/cmake-audit/find-ocx-cmake-shape-and-contracts.md') + `

Run from /home/mherwig/dev/find_ocx. Exclude .git, build/, docs/_build, docs/.venv, .serena. The tree is dirty: run git status --short and git diff --stat first, and for every finding say whether it holds on HEAD, on the working tree, or both (git show HEAD:ocx.cmake gives the committed file). Read OCX-0.5-HANDOVER.md so you know what the in-flight change is.

Measurement axes:
1. File census: lines per file for ocx.cmake, Findocx.cmake, CMakeLists.txt, tests/*.cmake, tests/fixtures/**/CMakeLists.txt, examples/**/CMakeLists.txt, scripts/*.py, .github/workflows/*.yml, docs/*.rst, taskfile.yml, taskfiles/*.yml. Which files ship to consumers (release workflow: exactly which files) versus repo-internal.
2. Function census in ocx.cmake and Findocx.cmake: every function() and macro() with its line span, public versus private (double-underscore) naming, whether each uses cmake_parse_arguments (and with PARSE_ARGV or ARGN), how many return values via PARENT_SCOPE versus CACHE versus set_property(GLOBAL), and which functions set CACHE variables (list each cache variable, its type, its DOC, and whether FORCE is used). Count set(... PARENT_SCOPE), set(... CACHE ...), unset(... CACHE), and $CACHE{...} / DEFINED CACHE{...} reads. Count ENV{...} reads and writes and list every environment variable named.
3. Scoping and policy posture: include_guard kind; cmake_policy(PUSH/POP/VERSION) balance; every CMPxxxx named and where; cmake_minimum_required presence in the shipped module versus the harness; CMAKE_VERSION VERSION_LESS guards and the floor they enforce; what happens on CMake 3.15-3.18 in each of the two files; whether the module is safe under a caller's cmake_minimum_required below 3.19 (policy inheritance at function-definition time — cite the comment).
4. Quoting and list discipline: count if() tests with unquoted variable references, string(...) and list(...) calls, foreach forms, uses of the semicolon-list pitfalls (paths with semicolons, list(APPEND) with quoted lists), separate_arguments, and every place a user-supplied value is interpolated into a COMMAND. Cite each risky site.
5. Network and process surface: every file(DOWNLOAD ...) with its options present or absent (EXPECTED_HASH, TLS_VERIFY, TIMEOUT, INACTIVITY_TIMEOUT, STATUS, LOG, SHOW_PROGRESS, HTTPHEADER); every execute_process with its options (RESULT_VARIABLE, OUTPUT_VARIABLE, ERROR_VARIABLE, COMMAND_ERROR_IS_FATAL, TIMEOUT, OUTPUT_STRIP_TRAILING_WHITESPACE, ENCODING, WORKING_DIRECTORY); every file(ARCHIVE_EXTRACT); every string(JSON ...) with ERROR_VARIABLE or not; where sha256 is verified and where a download is trusted without a hash. Table with file:line.
6. Error taxonomy: every message(FATAL_ERROR|SEND_ERROR|WARNING|AUTHOR_WARNING|DEPRECATION|STATUS|VERBOSE|DEBUG) count; the message prefix convention; the sysexit-to-hint table in __ocx_default_hint (quote it) and which ocx exit codes it names; which failures are fatal versus warnings; whether any error path leaks a credential or a full environment. Compare with the ocx CLI exit-code contract documented in /home/mherwig/dev/rules_ocx/AGENTS.md (read-only) and say where the two projects diverge.
7. Memoization and reconfigure semantics: how a provisioning call is memoized across reconfigures (the __ocx_memo_* functions), what invalidates it (OCX_REFRESH, lock digest, toml mtime?), whether file(... ) dependencies use CMAKE_CONFIGURE_DEPENDS, and what tests/reconfigure_check.cmake asserts. Then the env-snapshot pattern (__ocx_snapshot_env): list every OCX_* knob, whether it is snapshotted, sticky, or passthrough, and whether the docs header table matches the code (drift table).
8. Platform posture: Windows handling (LOCALAPPDATA, .zip versus .tar.gz, .exe suffix, path separators, NMake versus Ninja comment in CI), macOS, the host-info detection (__ocx_host_info: which CMAKE_HOST_SYSTEM_* variables, how arm64 versus x86_64 is decided, what happens on musl or unknown). Which platforms CI actually runs (matrix in ci.yml) versus which the code claims to support.
9. The find_package seam: how <name>_ROOT is exported (CMP0074), whether the variable is normal or cache, what NO_ROOT does, how ocx_package composes with a later find_package / find_program / find_library, and whether CMAKE_PROGRAM_PATH or CMAKE_PREFIX_PATH is ever touched. What the Findocx.cmake find module does that a CONFIG package would do differently. Whether an imported executable target (ocx::ocx) is created and how.
10. Tests and CI: list the test families in CMakeLists.txt with what each asserts (read tests/helpers.cmake and each fixture), which are negative tests, which run only on Linux, which CMake versions they run against (and how those are provisioned — dogfooding through ocx.sh/kitware/cmake), whether -Werror=dev is applied everywhere, what the offline job proves, what the examples matrix proves, what is NOT tested (Windows path, mirror knobs, self-update against a real release, CMake 3.19 floor since mirror-cmake starts at 3.31 — cite the TODO). Docs freshness: does anything check the .rst header in ocx.cmake against docs/reference.rst (Sphinx CMake domain) — say how.
11. Doc-versus-code drift: README.md, docs/index.rst and the ocx.cmake .rst header versus the code: every knob or command documented but absent, or present but undocumented. Table.
12. Parity with rules_ocx (read-only, /home/mherwig/dev/rules_ocx): the public surface (ocx_project/ocx_package/ocx_index/ocx_bootstrap versus the extension's tag classes and repository rules), the env passthrough set (the docs header lists one; compare with rules_ocx's list), the pin versions (__OCX_PIN_VERSION versus rules_ocx's), the sysexit hint tables, and the reproducible-first defaults (floating tag policy). Table: concern | find_ocx | rules_ocx | same or diverged.

Headline numbers first. Every number with its command.`,
  },
  {
    key: 'fleet-inventory-and-bazel-overlap',
    prompt: PREAMBLE('inventory and faithful digesting of existing config and of the sibling research program; no judgment that becomes a rule') + '\n' +
      GROUND_CONTRACT('the fleet\'s CMake, C++ and package-manager footprint, its existing AI config, and the overlap with the Bazel program', RESEARCH + '/cmake-audit/fleet-inventory-and-bazel-overlap.md') + `

Measurement axes:
1. Fleet footprint under /home/mherwig/dev at maxdepth 6 (exclude .agents/worktrees, node_modules, .git, target, build, .venv, docs/.venv, docs/_build): every CMakeLists.txt, *.cmake, *.cmake.in, CMakePresets.json, CMakeUserPresets.json, conanfile.py, conanfile.txt, conandata.yml, conan.lock, vcpkg.json, vcpkg-configuration.json, HunterGate.cmake, CPM.cmake, .cmake-format*, .gersemirc, .clang-tidy, .clang-format; and every *.c, *.cc, *.cpp, *.cxx, *.h, *.hpp, *.hh file, grouped by repository with counts. Say for each hit whether it is a consumer, a probe, a vendored file, or scratch. The frame says: one CMake codebase (find_ocx), zero C++ codebases, zero package-manager manifests. Confirm or contradict with the counts.
2. Existing AI config touching the domain: every rule, skill, agent, ADR, research note, plan, AGENTS/CLAUDE file under any .claude/ or .agents/ in the fleet whose text mentions cmake, CMake, conan, vcpkg, hunter, CPM, ctest, cpack, find_package, or C++ (grep -rli, then grep -n for the lines). Start with /home/mherwig/dev/find_ocx/.claude/rules/*.md, /home/mherwig/dev/ocx-contrib/.claude/skills/create-mirror/ (its references mention cmake), /home/mherwig/dev/mirror-kitware/ (README, cmake/mirror.yml, cmake/CATALOG.md, cmake/metadata*.json), /home/mherwig/dev/ocx/website/src/docs (grep -rli cmake or find_ocx), and /home/mherwig/dev/rules_ocx/AGENTS.md where it mentions find_ocx or CMake. For each: path, size (lines), activation (always-on / glob / skill / ADR / docs), and a FAITHFUL DIGEST of its normative content quoted verbatim where short.
3. The CMake toolchain as an OCX product: from mirror-kitware/cmake/mirror.yml and metadata*.json and CATALOG.md — which CMake versions and cascade tags are published (versions.min, the tag grammar, skip_prereleases), which platforms and the measured glibc floor per arch, which binaries (cmake, ctest, cpack, ccmake, cmake-gui, cmcldeps), and how find_ocx's own ocx.toml and CMakeLists.txt consume it (cmake:3.31, cmake:4). Also whether ccache, ninja, sccache, conan, vcpkg, clang, gcc, mold, lld or any C++ toolchain piece is published as an OCX mirror (ls /home/mherwig/dev/ocx-contrib/, grep the mirror names; read the mirror-ccache and mirror-ninja specs if present). Table: tool | mirrored? | versions | platforms | source.
4. The lore catalog's sibling rule sets at ` + ROOT + `/rules/: every glob in rust-cargo.md, python-packaging.md, typescript-packaging.md, docs-quality.md (frontmatter paths:), and every rule row in any rules/**/*.md whose text mentions a build system, CMake, Bazel, a lockfile, hermeticity, reproducibility, pinning, sha256, vendoring, or CI caching (grep -n -i). Report the overlap surface a CMake or C++ packaging rule would have to avoid duplicating, and the rule-ID prefixes in use (grep -rhoE for the ID pattern) to confirm CMK- is free.
5. The Bazel program's coverage ledger (read-only, ` + BAZEL_RESEARCH + `): read bazel-frame.md in full, bazel-topic-map.md sections "L. cpp.md", "Artifact set decision", "Group 9 — bazel-cpp" (the three dive briefs), "Deferred", "Questions for the owner", "Explicitly not a defect"; grep -n -i for cmake, conan, vcpkg, foreign_cc, autotools, pkg-config across bazel-topic-map.md, bazel-topic-map/*.md and bazel-audit/*.md. Produce a ledger table: Bazel row or brief (M-L-nn or dive 9.x) | what the Bazel program will cover | what it explicitly leaves to a CMake-side treatment | the exact sentence that draws the line, with file:line. Then one paragraph: which CMake-side questions the Bazel corpus already raised but does not own (this is the seam this program must cover), and which it owns outright (this program must not re-derive).
6. rules_ocx as the design twin of find_ocx (read-only): from /home/mherwig/dev/rules_ocx/AGENTS.md, README.md and ocx/*.bzl — the public surface, the env passthrough list, the exit-code hint table, the reproducible-first policy, the pin version and the bump script (scripts/bump_ocx.py) — as a table that the find_ocx audit (a sibling worker writes cmake-audit/find-ocx-cmake-shape-and-contracts.md concurrently; do not read or write it) can be compared against later. Quote the sentence in find_ocx/OCX-0.5-HANDOVER.md that says find_ocx mirrors rules_ocx.
7. What the fleet's own docs claim find_ocx is FOR, versus Conan tool_requires and vcpkg host dependencies: quote every positioning sentence in find_ocx/README.md, docs/index.rst, and the ocx website docs (grep -rn -i "cmake" /home/mherwig/dev/ocx/website/src/docs). Do not evaluate the claim; record it.
8. Gaps: which concerns from the frame's candidate list have NO existing config anywhere in the fleet. One line each.`,
  },
  {
    key: 'exemplar-cmake-shape',
    prompt: PREAMBLE('counting CMake idioms across a 46-repo corpus with grep and small scripts; volume measurement, no rule decisions') + '\n' +
      GROUND_CONTRACT('the exemplar corpus at ' + EXEMPLARS + ' (CMake language and buildsystem shape)', RESEARCH + '/cmake-audit/exemplar-cmake-shape.md') + `

The corpus: one directory per upstream repository, named owner__repo, cloned with --filter=blob:none --depth 1 and a sparse checkout of build and config files (CMakeLists.txt, *.cmake, *.cmake.in, presets, Conan and vcpkg manifests, Bazel files, .github, cmake/ directories, lint configs). Run git -C <dir> rev-parse --short=10 HEAD for the sha you cite. Run git -C <dir> ls-tree -r --name-only HEAD to see EVERY tracked path even when not checked out, and git -C <dir> show HEAD:<path> to read any file lazily. Measure files only. NEVER run cmake, conan, vcpkg, bazel or any build. A measurement script you write goes under ` + RESEARCH + `/cmake-audit/scratch/ (name it shape-<axis>.sh; emit TSV next to it) so every number is re-runnable; inline the command next to each result.

First, produce and save ` + EXEMPLAR_TABLE + ` (a sibling worker on dependency shape reads it, so write it in your first ten minutes): repo | sha | CMake? (count of CMakeLists.txt) | Bazel? (MODULE.bazel/BUILD present) | conanfile/vcpkg.json/CPM/Hunter present (y/n each) | checked-out file count | lowest cmake_minimum_required in the root CMakeLists.txt. A repo whose clone failed (no .git) is listed as failed, not silently dropped.

Measurement axes, each as aggregate counts across the corpus (n of 46) plus a per-repo table where it varies:
1. Version floors: the root cmake_minimum_required in every repo (exact form: single version, version...range, or absent), the minimum and maximum across the corpus, how many are below 3.5 (break on CMake 4.0), how many use the range form, how many set CMAKE_POLICY_VERSION_MINIMUM or CMAKE_POLICY_DEFAULT_CMPxxxx, how many call cmake_policy(SET CMPxxxx ...) and which policies (histogram), how many use if(POLICY ...).
2. Project declaration: project() with VERSION, LANGUAGES, DESCRIPTION, HOMEPAGE_URL (counts); the PROJECT_IS_TOP_LEVEL or CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR guard (counts, which form); include(CTest) versus enable_testing(); BUILD_TESTING guard on tests.
3. Language standard: CMAKE_CXX_STANDARD set globally versus target_compile_features(... cxx_std_NN) per target (counts of each, which NN values), CMAKE_CXX_EXTENSIONS OFF, CMAKE_CXX_STANDARD_REQUIRED ON, C standard equivalents.
4. Target-based versus directory-based commands, corpus-wide counts with grep -c summed: include_directories versus target_include_directories; add_definitions versus target_compile_definitions; add_compile_options versus target_compile_options; link_directories; link_libraries; CMAKE_CXX_FLAGS mutation (set(CMAKE_CXX_FLAGS or string(APPEND CMAKE_CXX_FLAGS); target_link_libraries calls with a PUBLIC/PRIVATE/INTERFACE keyword versus without (a regex that catches the plain signature); add_library kinds (STATIC/SHARED/MODULE/OBJECT/INTERFACE/ALIAS/none), ALIAS targets with a namespace (Foo::foo) count, add_executable count; BUILD_SHARED_LIBS references and whether any repo forces it for its subprojects; generator-expression density (count of $< occurrences per 100 CMake lines, per repo).
5. Sources: file(GLOB or GLOB_RECURSE used for source lists (count; how many carry CONFIGURE_DEPENDS), target_sources usage, target_sources(FILE_SET ...) usage (HEADERS versus CXX_MODULES), CMAKE_CXX_SCAN_FOR_MODULES, import std or CMAKE_EXPERIMENTAL_CXX_IMPORT_STD.
6. Options and cache: option() count and prefix discipline (what fraction of option names start with the project's own prefix), CMAKE_DEPENDENT_OPTION use, set(... CACHE ... FORCE) count, unset(... CACHE), mark_as_advanced.
7. Functions and macros: function() versus macro() counts, cmake_parse_arguments with PARSE_ARGV versus ARGN, PARENT_SCOPE returns, set_property(GLOBAL PROPERTY ...) as a return channel, block() usage, include_guard usage, message(FATAL_ERROR|SEND_ERROR|WARNING|AUTHOR_WARNING|DEPRECATION) counts, CMAKE_MESSAGE_CONTEXT use.
8. Install and export: install(TARGETS ... EXPORT), install(EXPORT ...), install(FILES/DIRECTORY), export(EXPORT/TARGETS), include(GNUInstallDirs), include(CMakePackageConfigHelpers), configure_package_config_file, write_basic_package_version_file with which COMPATIBILITY, <Pkg>Config.cmake.in versus <pkg>-config.cmake naming, install(PACKAGE_INFO ...) (CPS), NAMESPACE on install(EXPORT), CMAKE_INSTALL_RPATH / CMAKE_BUILD_RPATH / INSTALL_RPATH_USE_LINK_PATH / CMAKE_MACOSX_RPATH, CMAKE_POSITION_INDEPENDENT_CODE, include(GenerateExportHeader) / generate_export_header, CMAKE_CXX_VISIBILITY_PRESET / VISIBILITY_INLINES_HIDDEN, WINDOWS_EXPORT_ALL_SYMBOLS, CMAKE_MSVC_RUNTIME_LIBRARY, CheckIPOSupported / INTERPROCEDURAL_OPTIMIZATION, CMAKE_LINK_LIBRARIES_ONLY_TARGETS, CMAKE_COMPILE_WARNING_AS_ERROR versus -Werror literals, CMAKE_EXPORT_COMPILE_COMMANDS, CMAKE_<LANG>_COMPILER_LAUNCHER (ccache/sccache), CMAKE_UNITY_BUILD, precompiled headers (target_precompile_headers).
9. Testing and packaging: add_test count, gtest_discover_tests / catch_discover_tests / doctest_discover_tests, CTest properties used (TIMEOUT, LABELS, WILL_FAIL, ENVIRONMENT, WORKING_DIRECTORY, FIXTURES_*), CTestConfig.cmake / CDash, CPack usage (include(CPack), CPACK_ variables, CPACK_GENERATOR values), cmake --workflow presets.
10. Presets: CMakePresets.json presence, schema version, number of configure/build/test/package/workflow presets, use of inherits, hidden presets, toolchainFile, cacheVariables commonly set, condition blocks, CMakeUserPresets.json committed or gitignored (check .gitignore).
11. Lint and format configs: .cmake-format.yaml / .cmake-format.py / cmake-format.yaml, .gersemirc, cmake-lint in .pre-commit-config.yaml, .clang-tidy, .clang-format presence; -Werror=dev or --warn-uninitialized in CI workflows (grep the .github/workflows).
12. Cohesion of the largest CMake files: the top 5 CMakeLists.txt or *.cmake by line count across the corpus, each with a one-paragraph judgment (what it does, how many concerns) and its function list with line spans.

Headline numbers first. Every count with its command. A corpus-wide practice adopted by fewer than a quarter of the strict projects is a finding; so is one adopted by more than three quarters.`,
  },
  {
    key: 'exemplar-deps-and-dual-build',
    prompt: PREAMBLE('counting dependency-acquisition and dual-build patterns across a 46-repo corpus; volume measurement, no rule decisions') + '\n' +
      GROUND_CONTRACT('the exemplar corpus at ' + EXEMPLARS + ' (dependency acquisition, package managers, CMake-and-Bazel dual builds, CI)', RESEARCH + '/cmake-audit/exemplar-deps-and-dual-build.md') + `

The corpus: one directory per upstream repository, named owner__repo, cloned with --filter=blob:none --depth 1 and a sparse checkout of build and config files. Run git -C <dir> rev-parse --short=10 HEAD for the sha you cite. Run git -C <dir> ls-tree -r --name-only HEAD to see EVERY tracked path even when not checked out, and git -C <dir> show HEAD:<path> to read any file lazily. Measure files only. NEVER run cmake, conan, vcpkg, bazel or any build. A measurement script you write goes under ` + RESEARCH + `/cmake-audit/scratch/ (name it deps-<axis>.sh; emit TSV next to it). A sibling worker writes ` + EXEMPLAR_TABLE + ` (repo | sha | build systems | manifests present); wait up to five minutes for it to appear and reuse it rather than re-deriving; if it has not appeared, derive your own table and say so.

Measurement axes, each as aggregate counts (n of 46) plus per-repo tables where it varies:
1. find_package: total calls; how many with CONFIG, MODULE, REQUIRED, COMPONENTS, a version, a version range (1.2...3.0), GLOBAL, QUIET; how many Find<Pkg>.cmake modules each repo ships in its own cmake/ directory (and for which packages — a histogram of package names across the corpus: fmt, spdlog, ZLIB, OpenSSL, Threads, Python, GTest ...); CMAKE_FIND_PACKAGE_PREFER_CONFIG, CMAKE_PREFIX_PATH or <Pkg>_ROOT or <Pkg>_DIR manipulation inside CMake code, CMAKE_MODULE_PATH appends.
2. FetchContent: FetchContent_Declare count; the pin shape per declaration (GIT_TAG a full commit hash / a version tag / a branch name; URL with URL_HASH / without); FIND_PACKAGE_ARGS, OVERRIDE_FIND_PACKAGE, SYSTEM, EXCLUDE_FROM_ALL, DOWNLOAD_EXTRACT_TIMESTAMP, SOURCE_SUBDIR; FetchContent_MakeAvailable versus the old Populate pattern; FETCHCONTENT_SOURCE_DIR_<X> / FETCHCONTENT_TRY_FIND_PACKAGE_MODE; ExternalProject_Add count and whether at configure time (execute_process driving it) or build time.
3. CPM.cmake: repos vendoring cmake/CPM.cmake (and which CPM version string inside the file), CPMAddPackage count, shorthand URI form versus long form, VERSION pins versus GIT_TAG, CPM_SOURCE_CACHE, CPM_USE_LOCAL_PACKAGES, CPM_DOWNLOAD_ALL, CPMUsePackageLock / package-lock.cmake, CPMLicenses.
4. Conan: conanfile.py / conanfile.txt / conandata.yml / conan.lock presence per repo; in each conanfile.py: requires, tool_requires / build_requires, test_requires, generators named (CMakeDeps, CMakeToolchain, CMakeConfigDeps, PkgConfigDeps, BazelDeps, BazelToolchain), layout() and cmake_layout, package_id() customisation, settings and options declared, python_requires, the Conan 1 versus Conan 2 API markers (from conan import ConanFile versus from conans import ConanFile; conan.tools.cmake versus the legacy cmake helper). For conan-io__conan-center-index: sample 40 recipes with a deterministic rule (the first 40 alphabetically under recipes/ that have a conanfile.py) and count the same markers; note the recipe layout (config.yml, all/conandata.yml, test_package/CMakeLists.txt). For conan-io__conan and conan-io__cmake-conan: list the CMake integration files they ship (conan_provider.cmake, conan.cmake) and the CMake versions they require.
5. vcpkg: vcpkg.json presence per repo; fields used (name, version / version-string / version-semver / version-date, builtin-baseline, dependencies with host: true, features, default-features, overrides, license, supports, port-version); vcpkg-configuration.json registries (kinds: builtin, git, filesystem, artifact); VCPKG_CHAINLOAD_TOOLCHAIN_FILE, VCPKG_MANIFEST_FEATURES, VCPKG_MANIFEST_MODE, VCPKG_TARGET_TRIPLET, VCPKG_OVERLAY_PORTS, VCPKG_BINARY_SOURCES, X_VCPKG_ASSET_SOURCES references in presets and CI; toolchainFile pointing at scripts/buildsystems/vcpkg.cmake. For microsoft__vcpkg: sample 40 ports deterministically (first 40 alphabetically under ports/ with a portfile.cmake) and count vcpkg_cmake_configure, vcpkg_cmake_install, vcpkg_cmake_config_fixup, vcpkg_fixup_pkgconfig, vcpkg_copy_pdbs, vcpkg_from_github with SHA512, OPTIONS -D... passed, usage files, and the maintainer-guide file's location (docs/ or in vcpkg-docs). For microsoft__vcpkg-tool: only the CMake it builds itself with.
6. Hunter: HunterGate.cmake presence anywhere in the corpus, hunter_add_package calls, cmake/Hunter/config.cmake; for cpp-pm__hunter: the number of packages under cmake/projects/, the last commit date (git -C <dir> log -1 --format=%cI), releases.txt or the VERSION scheme, and how HunterGate pins (URL + SHA1).
7. Dependency providers and toolchain files: cmake_language(SET_DEPENDENCY_PROVIDER ...) or CMAKE_PROJECT_TOP_LEVEL_INCLUDES references; CMAKE_TOOLCHAIN_FILE references in presets, CI and CMake code; toolchain files shipped under cmake/ (count, and what they set: compilers, sysroot, CMAKE_SYSTEM_NAME for cross builds); pkg_check_modules / FindPkgConfig; vendored third-party directories (third_party/, thirdparty/, external/, extern/, deps/, vendor/ — list which repos and how many subdirectories) and git submodules (.gitmodules entries per repo).
8. Dual build systems: every repo with BOTH a root CMakeLists.txt and MODULE.bazel / WORKSPACE / BUILD.bazel: name them; count cc_library + cc_binary + cc_test targets (grep across BUILD files) versus add_library + add_executable + add_test in CMake; list the mechanisms that keep them in sync (a script under cmake/ or bazel/ or tools/, a CI parity job, a doc that says which is primary, generated CMake from Bazel or the reverse — read the workflow files and any README under cmake/ or bazel/); the MODULE.bazel bazel_dep list versus the CMake dependency list for the same repo (drift table: dependency | Bazel version | CMake mechanism and pin | same version? y/n/unknown). Then the Bazel-only rulesets in the corpus (bazel-contrib__rules_foreign_cc): which CMake versions it bundles or expects, what its cmake() rule documentation says a CMake project must satisfy (read its docs/ and examples/), and its most recent release tag and date.
9. CI census: per repo, the .github/workflows (or .gitlab-ci.yml) matrix for CMake: which CMake versions are installed and how (lukka/get-cmake, jwlawson/actions-setup-cmake, pip install cmake, apt, the runner default, a container), generators used (Ninja, Unix Makefiles, Visual Studio, Xcode, Ninja Multi-Config), cmake --preset use, -Werror=dev or --warn-uninitialized, CMAKE_BUILD_TYPE matrix values, sanitizer jobs (-fsanitize in flags or a preset), an install-tree consumption test (a job that installs then builds a consumer against the installed package: grep for --install and a second configure with CMAKE_PREFIX_PATH), ccache/sccache in CI (hendrikmuhs/ccache-action, mozilla-actions/sccache-action), vcpkg/conan caching actions (lukka/run-vcpkg, conan cache save/restore, actions/cache keyed on vcpkg.json or conan.lock), and the count of OS in each matrix.
10. Lock and pin posture summary: for every dependency mechanism found (find_package, FetchContent, CPM, Conan, vcpkg, Hunter, submodule, vendored), how many declarations are content-pinned (hash), version-pinned (exact tag), range-pinned, or floating (branch, latest, no version). One table, corpus-wide, with the counting regex shown.

Headline numbers first. Every count with its command. Where a repo uses two mechanisms for the same library (for example FetchContent and find_package of the same name), list it — that is the finding the frame suspects but has not verified.`,
  },
]

// ---------------------------------------------------------------- Scout
const SCOUTS = [
  {
    key: 'canonical-cmake',
    corpus: `CMake's own canonical documentation and the canonical books — the curriculum, as a table of contents, plus a full sweep of the policy catalogue.
Fetch the raw reStructuredText under https://gitlab.kitware.com/cmake/cmake/-/raw/master/Help/ (or the rendered https://cmake.org/cmake/help/latest/) for EVERY manual and list its sections: cmake-buildsystem(7), cmake-packages(7) (Config packages versus Find modules, package registry, version files, dependency providers), cmake-policies(7), cmake-presets(7) (every schema version and what it added), cmake-toolchains(7), cmake-language(7) (quoting, lists, variable references, scopes, block()), cmake-variables(7) (the CMAKE_* families that matter: CMAKE_<LANG>_STANDARD, CMAKE_BUILD_TYPE, CMAKE_POSITION_INDEPENDENT_CODE, CMAKE_LINK_LIBRARIES_ONLY_TARGETS, CMAKE_EXPORT_COMPILE_COMMANDS, CMAKE_<LANG>_COMPILER_LAUNCHER, CMAKE_COMPILE_WARNING_AS_ERROR, CMAKE_FIND_* controls, CMAKE_POLICY_VERSION_MINIMUM), cmake-properties(7) (target properties that carry usage requirements), cmake-modules(7) (FetchContent, ExternalProject, GNUInstallDirs, CMakePackageConfigHelpers, GenerateExportHeader, CheckIPOSupported, CMakeDependentOption, CTest, CPack, FindPkgConfig, FindPython, FetchContent's FIND_PACKAGE_ARGS and OVERRIDE_FIND_PACKAGE), cmake-generator-expressions(7), cmake-developer(7) (find-module authoring rules), cmake-file-api(7), cmake-env-variables(7), cmake-configure-log(7), cmake-instrumentation(7) if present, cmake(1) (every mode: -S/-B, -P script mode, -E, --workflow, --preset, --fresh, -Werror=dev, -Wdev, --warn-uninitialized, --trace-expand, --debug-find, --debug-trycompile, --profiling-output, --install, --build), ctest(1) (--test-dir, -j, --output-on-failure, --repeat, --timeout, resource specs, --build-and-test), cpack(1), and the experimental features documentation (Help/dev/experimental.rst: CPS / install(PACKAGE_INFO), import std, cmake_pkg_config) with the version each is gated on.
Then the policy catalogue sweep (a core deliverable): enumerate EVERY policy CMP0000 through the newest in cmake-policies(7) as a table: policy | introduced in | one line on the mistake it fixes | still a live concern for a project whose floor is 3.19 or higher? | which command or variable it governs. Policies are a taxonomy of past mistakes; the rows still live above a 3.19 floor are the candidate topics.
Then the books, by table of contents: Professional CMake: A Practical Guide (Craig Scott; the public TOC at https://crascit.com/professional-cmake/ — every chapter is a candidate), Modern CMake for C++ 2nd edition (Rafal Swidzinski; publisher TOC), CMake Cookbook (Bast and Di Remigio; the GitHub repo), An Introduction to Modern CMake (https://cliutils.gitlab.io/modern-cmake/ — every page), Effective Modern CMake (Manuel Binna's gist), the official CMake tutorial steps (Help/guide/tutorial), the Kitware "Mastering CMake" book TOC, and Kitware's own Modules/readme.txt or cmake-developer conventions for module authors.
Every page, chapter, policy and checklist item is a candidate topic. Where a page states a rule ("do not", "must", "prefer", "deprecated"), quote it. Note which CMake minor each piece of guidance requires, and which pages predate 4.0.`,
  },
  {
    key: 'package-managers-canonical',
    corpus: `The package managers' own documentation — Conan 2, vcpkg, Hunter and its cpp-pm fork, CPM.cmake, dependency providers — plus the tool-provisioner comparison set.
Conan 2 (https://docs.conan.io/2/): fetch the navigation and list every page under Tutorial, Reference (conanfile attributes and methods: requires, tool_requires, test_requires, package_id, layout, generate, build, package, package_info, validate; generators: CMakeDeps, CMakeToolchain, CMakeConfigDeps (experimental status and version), PkgConfigDeps, BazelDeps, BazelToolchain, MesonToolchain; conan.tools.cmake; profiles and settings.yml; options; lockfiles; remotes; the conan cache and conan cache save/restore; conan graph info/build-order/outdated; conan audit; conan list and pkglist; conan workspace), Integrations (CMake including cmake-conan's conan_provider.cmake and its stated limitations; Bazel; Meson; Visual Studio), Knowledge (FAQ, cheatsheet, guidelines for recipe authors), and the Conan Center Index contributing docs (https://github.com/conan-io/conan-center-index/tree/master/docs — every rule a recipe must satisfy). Record for each: the Conan version it applies to, and anything marked experimental, deprecated or Conan-1-only.
vcpkg (https://learn.microsoft.com/vcpkg/): fetch the navigation and list every page under Concepts (manifest mode versus classic mode, ports, triplets, features, versioning and baselines, registries, overlay ports and triplets, binary caching, asset caching, the build process), Reference (vcpkg.json schema — every field; vcpkg-configuration.json; triplet variables; the CMake integration variables VCPKG_TARGET_TRIPLET, VCPKG_HOST_TRIPLET, VCPKG_CHAINLOAD_TOOLCHAIN_FILE, VCPKG_MANIFEST_MODE, VCPKG_MANIFEST_FEATURES, VCPKG_INSTALLED_DIR, VCPKG_OVERLAY_PORTS; VCPKG_BINARY_SOURCES providers; X_VCPKG_ASSET_SOURCES; the vcpkg_* portfile helper functions; the CLI reference), Users (CMake integration via the toolchain file, MSBuild, manual integration), Contributing / maintainer guide (every rule a port must satisfy), and the release notes or changelog cadence. Note which features are marked experimental (x- prefix).
Hunter (https://hunter.readthedocs.io/ and https://github.com/cpp-pm/hunter): the HunterGate mechanism (URL + SHA1 pin), config.cmake, hunter_add_package, toolchain-id and the binary cache, the package list size, the last release and the commit activity on cpp-pm/hunter versus ruslo/hunter in 2024-2026 — is it maintained? State the evidence.
CPM.cmake (https://github.com/cpm-cmake/CPM.cmake — README, wiki, releases): CPMAddPackage long and shorthand forms, CPMFindPackage, CPM_SOURCE_CACHE, CPM_USE_LOCAL_PACKAGES, CPM_LOCAL_PACKAGES_ONLY, CPM_DOWNLOAD_ALL, CPM_DONT_UPDATE_MODULE_PATH, package locks (CPMUsePackageLock), CPMLicenses.cmake, how it wraps FetchContent, its stated limitations, current version and release cadence.
Dependency providers as the neutral seam: the cmake-packages(7) and cmake(1) documentation of cmake_language(SET_DEPENDENCY_PROVIDER) and CMAKE_PROJECT_TOP_LEVEL_INCLUDES, and how Conan, vcpkg and CPM each do or do not use it.
Comparison and tool-provisioning set, briefly and by their own docs: Meson wrapdb and Meson's CMake subproject support, build2 and cppget.org, xmake and xrepo, pixi and conda-forge compilers as a C++ toolchain provisioner, Spack, Nix (nixpkgs cmake setup hook), and OCX find_ocx (read /home/mherwig/dev/find_ocx/README.md) versus Conan tool_requires versus vcpkg host dependencies for provisioning TOOLS rather than libraries: which knobs each exposes for reproducibility (lockfile, hash, mirror, offline).
Every page and every schema field is a candidate. Record who owns which half of the dependency problem (source acquisition, binary caching, ABI model, lock format, transitive propagation into CMake targets) per manager, as a comparison table.`,
  },
  {
    key: 'codified-lint-and-policies',
    corpus: `Codified practice — rules an organisation already thought worth ENFORCING — and full catalogue sweeps of the CMake linters.
1. Catalogue sweep: cmake-lint from cmakelang (https://github.com/cheshirekow/cmake_format — fetch the raw lint documentation and the source listing of every lint code C0xxx, E0xxx, E1xxx, R0xxx, W0xxx: name | what it says in one line | still correct on CMake 4.x? | maintained? (last release date) | worth adopting as a rule row?), cmake-format configuration knobs, gersemi (https://github.com/BlankSpruce/gersemi — what it formats, what it refuses, its definitions-file mechanism and its release cadence), and the developer warnings CMake itself emits under -Wdev / -Werror=dev and --warn-uninitialized / --warn-unused-vars (find the AUTHOR_WARNING message sites in the CMake source tree Source/ via GitLab search or the documentation of each: what triggers each). The "no" and "not enforced anywhere" rows are the finding.
2. Organisational CMake style guides and conventions, each as rows (rule | who enforces it | how — lint, review, CI): the LLVM CMake Primer (https://llvm.org/docs/CMakePrimer.html) and LLVM's CMake conventions; KDE Extra CMake Modules (https://api.kde.org/ecm/) and the KDE Frameworks CMake policies (KDECompilerSettings, KDECMakeSettings, KDE_COMPILERSETTINGS_LEVEL); Qt 6's public CMake API conventions and the qt_* policies (QTP0001 ...); Boost's CMake build (boostorg/cmake) conventions; Kitware's own CMake source-tree conventions for Modules (Help/dev/maint.rst, Modules/readme.txt, the find-module requirements in cmake-developer(7)); the vcpkg maintainer guide (https://learn.microsoft.com/vcpkg/contributing/maintainer-guide — every MUST and SHOULD, especially what a port's CMake must NOT do: absolute paths, downloads at build, unfixed Config files, non-relocatable installs); the Conan Center hooks and linter (https://github.com/conan-io/hooks and the conan-center-index docs/ linter rules — each check is a codified rule); the cpp-best-practices cmake_template and project_options defaults (https://github.com/cpp-best-practices/cmake_template, https://github.com/aminya/project_options — the warnings, sanitizer, hardening and static-analysis defaults they codify); friendlyanon/cmake-init conventions (dev mode, PROJECT_IS_TOP_LEVEL, the <pkg>-config naming, install-tree tests).
3. Distribution packaging rules for CMake projects: Debian's CMake packaging guidance (dh_cmake, the multiarch rules, CMAKE_BUILD_TYPE=None, no bundled libraries), Fedora's CMake packaging guidelines (%cmake macros, forbidden -DCMAKE_INSTALL_LIBDIR mistakes), Homebrew's cmake formula conventions (std_cmake_args), conda-forge's CMake recipes; and what each says a well-behaved upstream CMake project must support (GNUInstallDirs, respecting CMAKE_INSTALL_PREFIX and DESTDIR, no FetchContent at configure, BUILD_TESTING opt-out, no forced BUILD_SHARED_LIBS).
4. Supply-chain and reproducibility codification: OpenSSF Scorecard Pinned-Dependencies as applied to FetchContent and ExternalProject (what it checks), SLSA and reproducible-builds.org guidance for CMake (embedded paths, -ffile-prefix-map, timestamps, CMAKE_BUILD_RPATH), the CMake documentation on CMAKE_DEBUG_PREFIX_MAP if present, Google OSS-Fuzz's CMake integration rules, and any CISA / national-agency secure-build guidance naming CMake.
5. Bazel-side codified expectations of a CMake project (read-only, to draw the seam): rules_foreign_cc's cmake() rule documentation (https://github.com/bazel-contrib/rules_foreign_cc/tree/main/docs and the README) — what it requires of the wrapped project (install target, out_static_libs / out_shared_libs / out_include_dir declarations, the generate_args and cache_entries it forces, the working-directory and network constraints). Only the requirements ON THE CMAKE PROJECT; the Bazel program owns the rest.
For every codified rule record who enforces it and how (lint code, hook, presubmit, CI check), because "true and checkable" is exactly what a rule file needs.`,
  },
  {
    key: 'practitioner-and-failure',
    corpus: `Practitioner writing, conference talks and the failure corpus — argued positions with their reasoning, and the complaints that keep resurfacing. This corpus finds the topics no curriculum lists.
Practitioners (read the posts, extract the argued position): Craig Scott's blog (https://crascit.com/ — every post 2019-2026: target_sources, FetchContent and find_package integration, CMake 4.0 compatibility, cmake_minimum_required guidance, presets, install and export); Alex Reinking (https://alexreinking.com/ — "How to Use CMake Without the Agonizing Pain" parts 1 and 2, "Building a Dual Shared and Static Library with CMake", his CMake anti-pattern posts); Henry Schreiner (the HSF CMake training at https://hsf-training.github.io/hsf-training-cmake-webpage/ and the Modern CMake book; scikit-build-core's stance on CMake floors and presets); Daniel Pfeifer's "Effective CMake" (C++Now 2017 — the slides and the canonical rules); Mathieu Ropert ("Modern CMake" and "Using Modern CMake Patterns to Enforce a Good Modular Design", CppCon 2017); Deniz Bahadir ("More Modern CMake" 2018 and "Oh No! More Modern CMake" 2019, Meeting C++); the Kitware blog (https://www.kitware.com/blog/ — Ben Boeckel's C++20 modules series, Brad King, Kyle Edwards on presets, the CMake 4.0 announcement, CPS announcements); Jason Turner's cpp_starter_project and C++ Weekly CMake episodes; Jeff Trull; Bret Brown (Bloomberg, on packaging and CPS at CppCon 2023-2025); the CPS specification authors (Matthew Woehlke, Stephen Kelly) and their talks; Diego Rodriguez-Losada, Luis Caro and Carlos Zoido (Conan; CppCon and Meeting C++ 2023-2025 talks; the Conan blog https://blog.conan.io/ 2023-2026); Robert Schumacher, Billy O'Neal, Augustin Popa and Javier Matos (vcpkg; the vcpkg blog on devblogs.microsoft.com/cppblog and their CppCon talks); Lars Melchior (CPM.cmake) on why CPM exists; the "C++ package managers: the ultimate roundup" style comparison talks and posts of 2023-2026; the JetBrains C++ Developer Ecosystem survey 2023, 2024 and 2025 (package-manager and build-system adoption percentages — quote the numbers and the sample size) and the ISO C++ Foundation annual "lite" survey (2024, 2025, 2026 if out); the Meeting C++ / CppCon / C++Now / ACCU talk lists 2023-2026 filtered for CMake, Conan, vcpkg, packaging, modules (title | speaker | argued position | link).
Failure corpus (read the threads, not the titles): the top-voted CMake questions on Stack Overflow as a taxonomy (fetch the tag's votes-sorted page: what people cannot do); Hacker News threads on CMake and on C++ package managers with more than 100 points 2022-2026 (search hn.algolia.com; read the top comments); r/cpp recurring threads ("why is CMake like this", vcpkg versus Conan, CPM versus FetchContent); the most-thumbed open and closed issues on gitlab.kitware.com/cmake/cmake (sort by upvotes or weight; read at least 20), on conan-io/conan and microsoft/vcpkg (sort by reactions; read at least 20 each, use gh api read-only), cpm-cmake/CPM.cmake issues, cpp-pm/hunter issues (what killed adoption), conan-io/cmake-conan issues about conan_provider.cmake, and bazel-contrib/rules_foreign_cc issues that describe what a CMake project did that broke the wrap (absolute paths in Config files, configure-time downloads, ignored CMAKE_INSTALL_PREFIX, find_package on host libraries, generated headers in the source tree) — only the CMake-side causes.
Specific failure classes to run down with sources: two copies of one library when FetchContent and find_package meet; the CMAKE_TOOLCHAIN_FILE collision between vcpkg's toolchain and Conan's conan_toolchain.cmake and the chainload workaround; cppstd or CMAKE_CXX_STANDARD mismatch between a Conan profile and the consuming project and the ABI break it causes; vcpkg triplet mismatch (static versus dynamic CRT, x64-windows versus x64-windows-static) at link time; RPATH at install on Linux and macOS; BUILD_SHARED_LIBS leaking into subprojects; option() versus a normal variable (CMP0077); if() auto-dereference (CMP0054); file(GLOB) staleness; in-source builds; empty CMAKE_BUILD_TYPE; CMAKE_CXX_FLAGS global mutation; macro argument flattening and ARGN; PARENT_SCOPE return confusion; execute_process without RESULT_VARIABLE; generator expressions evaluated at configure time; GIT_TAG on a branch or a tag that moved; ExternalProject at configure time; cmake_minimum_required(VERSION 2.8) blowing up on 4.0 in a transitive dependency and the CMAKE_POLICY_VERSION_MINIMUM workaround; presets that only work with one generator; Windows path length and spaces; MSVC runtime mismatch; dual CMake-and-Bazel drift stories in abseil, gRPC, protobuf and googletest (issues where the two builds disagreed).
For each pain point: what breaks | root cause as the source states it | the fix or mitigation the source found | is there a mechanical check | source URL | still true as of ` + DATE + `? A pain point with a mechanical check is a P0 candidate. Where two practitioners disagree (FetchContent versus a package manager; CPM versus vcpkg versus Conan; Config packages versus Find modules; CMAKE_CXX_STANDARD globally versus per target; presets versus CI scripts; superbuilds; whether Hunter is dead), record both and the trend.`,
  },
  {
    key: 'recent-shifts',
    corpus: `Recent shifts — what changed in CMake, Conan, vcpkg, Hunter, CPM.cmake and the surrounding tooling in the last 24-36 months, and what older advice it invalidated.
Part A — CMake: read the release notes for every minor from 3.24 through the newest 4.x (https://cmake.org/cmake/help/latest/release/index.html and the per-version pages) and produce a "use X not Y in 2026" table with the version and date for each row: the 4.0 removal of compatibility with floors below 3.5 and CMAKE_POLICY_VERSION_MINIMUM as the escape hatch (and what 4.x did next); dependency providers and CMAKE_PROJECT_TOP_LEVEL_INCLUDES (3.24); FetchContent FIND_PACKAGE_ARGS, OVERRIDE_FIND_PACKAGE, SYSTEM and EXCLUDE_FROM_ALL (3.24-3.28); cmake --workflow and workflow presets (3.25) and every presets schema version through the newest; --fresh (3.24); block() (3.25); target_sources FILE_SET (3.23) and CXX_MODULES (3.28); C++20 named modules stable (3.28), import std experimental (3.30) and its status now; CMAKE_LINK_LIBRARIES_ONLY_TARGETS (3.23); CMAKE_COMPILE_WARNING_AS_ERROR (3.24); CMAKE_EXPORT_BUILD_DATABASE (3.31); cmake_pkg_config (3.31 experimental) and its status; install(PACKAGE_INFO) and the Common Package Specification (which 4.x, experimental gate, current status); find_package CPS consumption; CMAKE_<LANG>_COMPILER_LAUNCHER changes; ctest changes (--test-dir, resource groups, --repeat, instrumentation); the Makefile and Ninja generator changes; removed generators and deprecated commands; the CMAKE_EXPERIMENTAL_* UUID gates and how they change per release. For each: the old advice it invalidates and the migration action.
Part B — Conan: the Conan 2 release history (https://github.com/conan-io/conan/releases and https://docs.conan.io/2/changelog.html) from 2.0 (2023-02) to the newest 2.x: which features arrived when (conan_provider.cmake and its status, CMakeConfigDeps, workspaces, conan audit and SBOM, conan cache save/restore, tool_requires in profiles, the Bazel 7/8/9 generator rewrites for Bzlmod, lockfile changes, package_id defaults and the compatibility plugin, python_requires changes, the deprecations); Conan 1 end-of-life status; the Conan Center Index migration state (how many recipes Conan-2-ready, their published number).
Part C — vcpkg: the vcpkg release notes (https://github.com/microsoft/vcpkg/releases, monthly, and microsoft/vcpkg-tool releases) 2024-2026: registries and versioning changes, vcpkg-configuration.json, binary-cache providers added or removed (GHA cache, Azure, NuGet, files, http, AWS, GCS, COS), asset caching, artifact mode / vcpkg-ce status (deprecated?), the x- experimental features graduated or removed, the license field and SPDX, manifest overrides, the Visual Studio integration changes, triplet additions (arm64 hosts, Android, Emscripten), and the port count.
Part D — the rest: cpp-pm/hunter release and commit activity 2023-2026 (is it maintained?); CPM.cmake releases (0.38 to the newest; what changed); cmakelang / cmake-format maintenance status versus gersemi adoption; Ninja 1.12 and 1.13 changes relevant to CMake; ccache and sccache CMake integration changes; Meson, build2, xmake and pixi movements that touch CMake users; compiler support for import std (MSVC, Clang 18-21, GCC 15) as it gates CMake guidance; the JetBrains 2024 and 2025 survey deltas for CMake, vcpkg, Conan and "no package manager" adoption; Bazel 9 and rules_foreign_cc releases only as they change what a CMake project must satisfy (one row).
Every row: version | date | what changed | old advice invalidated | migration action | source URL. Mark anything still experimental. This scout also owns the era check: state plainly which CMake, Conan, vcpkg, CPM and Hunter versions are current on ` + DATE + `, with the URL that proves it.`,
  },
]

// ---------------------------------------------------------------- Run
phase('Ground')
log('Wave 1: ' + GROUNDERS.length + ' grounders + ' + SCOUTS.length + ' scouts, all sonnet, concurrent')

const groundThunks = GROUNDERS.map(g => () =>
  agent(g.prompt, { label: 'ground:' + g.key, phase: 'Ground', model: 'sonnet', schema: GROUND_SCHEMA })
    .then(r => (r ? { key: g.key, ...r } : null)))

const scoutThunks = SCOUTS.map(s => () =>
  agent(
    PREAMBLE('corpus survey and web reading — discovering topics, deciding nothing') + '\n' +
      SCOUT_CONTRACT(s.corpus, RESEARCH + '/cmake-topic-map/' + s.key + '.md'),
    { label: 'scout:' + s.key, phase: 'Scout', model: 'sonnet', schema: SCOUT_SCHEMA },
  ).then(r => (r ? { key: s.key, ...r } : null)))

const all = await parallel([...groundThunks, ...scoutThunks])
const ground = all.slice(0, GROUNDERS.length).filter(Boolean)
const scouts = all.slice(GROUNDERS.length).filter(Boolean)

const dropped = [
  ...GROUNDERS.filter((g, i) => !all[i]).map(g => 'ground:' + g.key),
  ...SCOUTS.filter((s, i) => !all[GROUNDERS.length + i]).map(s => 'scout:' + s.key),
]
if (dropped.length) log('DROPPED (returned null): ' + dropped.join(', '))

const totalCandidates = scouts.reduce((n, s) => n + (s.candidates ? s.candidates.length : 0), 0)
log('Ground: ' + ground.length + '/' + GROUNDERS.length + ' · Scouts: ' + scouts.length + '/' + SCOUTS.length + ' · candidates: ' + totalCandidates)

return { ground, scouts, dropped, totalCandidates }
