#!/usr/bin/env bash
# Builds exemplar-table.md: repo | sha | CMake? | Bazel? | conan/vcpkg/CPM/Hunter | file count | min cmake version
set -uo pipefail
CORPUS=/tmp/claude-1000/-home-mherwig-dev-grimoire-lore--agents-worktrees-java/c4f22277-6831-442c-8bc3-1be41a79fdff/scratchpad/exemplars
OUT=/home/mherwig/dev/grimoire-lore/.agents/worktrees/java/.agents/research/cmake-audit/scratch/exemplar-table.md

echo "# Exemplar corpus table" > "$OUT"
echo "" >> "$OUT"
echo "Generated by exemplar-table.sh. n=$(ls -d "$CORPUS"/*/ | wc -l)." >> "$OUT"
echo "" >> "$OUT"
echo "| repo | sha | CMakeLists.txt count | Bazel (MODULE.bazel/BUILD) | conanfile | vcpkg.json | CPM | Hunter | checked-out files | root cmake_minimum_required |" >> "$OUT"
echo "|---|---|---|---|---|---|---|---|---|---|" >> "$OUT"

for d in "$CORPUS"/*/; do
  repo=$(basename "$d")
  if [ ! -d "$d/.git" ]; then
    echo "| $repo | FAILED | - | - | - | - | - | - | - | clone failed (no .git) |" >> "$OUT"
    continue
  fi
  sha=$(git -C "$d" rev-parse --short=10 HEAD 2>/dev/null)
  # Capture the full tree listing ONCE into a variable, then grep the variable (not a
  # live pipe): with `pipefail` set, a `git ls-tree ... | grep -q` pipe can make grep's
  # early exit (on first match) SIGPIPE the still-writing git process, which under
  # pipefail flips a real match to a false "not found". Grepping a captured string has
  # no live upstream process to kill, so this class of false negative is impossible.
  tree=$(git -C "$d" ls-tree -r --name-only HEAD)
  cmake_count=$(echo "$tree" | grep -c 'CMakeLists\.txt$')
  bazel_present="n"
  echo "$tree" | grep -qE '(^|/)(MODULE\.bazel|BUILD|BUILD\.bazel)$' && bazel_present="y"
  conan_present="n"
  echo "$tree" | grep -qE '(^|/)conanfile\.(py|txt)$' && conan_present="y"
  vcpkg_present="n"
  echo "$tree" | grep -qE '(^|/)vcpkg\.json$' && vcpkg_present="y"
  cpm_present="n"
  echo "$tree" | grep -qiE '(^|/)CPM\.cmake$' && cpm_present="y"
  hunter_present="n"
  echo "$tree" | grep -qiE 'HunterGate\.cmake$|(^|/)cmake/Hunter' && hunter_present="y"
  checked_out=$(find "$d" -type f -not -path '*/.git/*' | wc -l)
  # find root CMakeLists.txt (top level, not in subdir) — same capture-then-grep rule
  root_tree=$(git -C "$d" ls-tree --name-only HEAD)
  root_cml=$(echo "$root_tree" | grep -x 'CMakeLists.txt' || true)
  minver="absent"
  if [ -n "$root_cml" ]; then
    content=$(git -C "$d" show HEAD:CMakeLists.txt 2>/dev/null)
    line=$(echo "$content" | grep -im1 'cmake_minimum_required' || true)
    if [ -n "$line" ]; then
      minver=$(echo "$line" | tr -d '\r' | sed -E 's/^[[:space:]]*//' | head -c 200)
    else
      minver="no cmake_minimum_required in root"
    fi
  fi
  # escape pipes in minver
  minver_esc=$(echo "$minver" | sed 's/|/\\|/g')
  echo "| $repo | $sha | $cmake_count | $bazel_present | $conan_present | $vcpkg_present | $cpm_present | $hunter_present | $checked_out | \`$minver_esc\` |" >> "$OUT"
done
echo "Done: $OUT"
