cmake_minimum_required(VERSION 3.25...4.4)
project(m2 LANGUAGES C)
add_library(m2 STATIC m2.c)
include(GNUInstallDirs)
include(CMakePackageConfigHelpers)
include(CheckCSourceCompiles)
check_c_source_compiles("int main(void){return 0;}" M2_OK)
install(TARGETS m2 EXPORT m2Targets)
install(EXPORT m2Targets NAMESPACE m2:: DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/m2)
message(STATUS "m2 reached end")
