cmake_minimum_required(VERSION 3.25...4.4)
project(m9 LANGUAGES NONE)
set(_saved "${CMAKE_POLICY_VERSION_MINIMUM}")
set(CMAKE_POLICY_VERSION_MINIMUM 3.10)
set(_savedwd "${CMAKE_WARN_DEPRECATED}")
set(CMAKE_WARN_DEPRECATED OFF)
add_subdirectory(dep)
set(CMAKE_POLICY_VERSION_MINIMUM "${_saved}")
set(CMAKE_WARN_DEPRECATED "${_savedwd}")
if(M9_SECOND)
  add_subdirectory(dep2)
endif()
message(STATUS "m9 reached end")
