cmake_minimum_required(VERSION 3.25)
project(f3 LANGUAGES CXX)
message(STATUS "[before find_package] CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}")
find_program(SEQ_PROG NAMES seq)
message(STATUS "[before find_package] find_program(seq)=${SEQ_PROG}")
find_library(EARLY_LIB NAMES anything_early)
message(STATUS "[before find_package] find_library(anything_early)=${EARLY_LIB}")
find_package(Beta REQUIRED)
message(STATUS "[after find_package] CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}")
if(TARGET Beta::beta)
  message(STATUS "HAVE_TARGET Beta::beta after find_package")
endif()
