cmake_minimum_required(VERSION 3.25...4.4)
project(picflags C)
option(OVERWRITE "overwrite CMAKE_C_FLAGS" OFF)
if(OVERWRITE)
  set(CMAKE_C_FLAGS "-Wall")
else()
  string(APPEND CMAKE_C_FLAGS " -Wall")
endif()
add_library(stat STATIC stat.c)
add_library(shared SHARED shared.c)
target_link_libraries(shared PRIVATE stat)
