cmake_minimum_required(VERSION 3.25)
project(p LANGUAGES NONE)
include(FetchContent)
set(depA_TESTS OFF)
set(depB_TESTS OFF)
FetchContent_Declare(depA SOURCE_DIR "/home/mherwig/.cache/cmake-measure-scratch/dependency-seam-consolidation/depA")
FetchContent_Declare(depB SOURCE_DIR "/home/mherwig/.cache/cmake-measure-scratch/dependency-seam-consolidation/depB")
set(CMAKE_POLICY_DEFAULT_CMP0077 NEW)
FetchContent_MakeAvailable(depA)
unset(CMAKE_POLICY_DEFAULT_CMP0077)
FetchContent_MakeAvailable(depB)
