cmake_minimum_required(VERSION 3.25...4.4)
project(green CXX)
if(NOT DEFINED CMAKE_CXX_STANDARD)
  set(CMAKE_CXX_STANDARD 20)
  set(CMAKE_CXX_STANDARD_REQUIRED ON)
  set(CMAKE_CXX_EXTENSIONS OFF)
endif()
include(GenerateExportHeader)
add_library(api api.cpp)
set_target_properties(api PROPERTIES CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN ON)
generate_export_header(api)
target_link_libraries(api PRIVATE Threads::Threads)
