cmake_minimum_required(VERSION 3.25...4.4)
project(vis CXX)
option(HIDE "use presets" OFF)
include(GenerateExportHeader)
add_library(api SHARED api.cpp)
generate_export_header(api BASE_NAME API)
target_include_directories(api PUBLIC ${CMAKE_CURRENT_BINARY_DIR} ${CMAKE_CURRENT_SOURCE_DIR})
if(HIDE)
  set_target_properties(api PROPERTIES CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN ON)
endif()
