cmake_minimum_required(VERSION 3.25)
set(VCPKG_MANIFEST_FEATURES tests)
project(good CXX)
if(NOT DEFINED CMAKE_CXX_STANDARD)
  set(CMAKE_CXX_STANDARD 20)
endif()
if(VCPKG_TARGET_TRIPLET MATCHES "-static$")
  set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
endif()
find_package(ZLIB CONFIG REQUIRED)
find_package(protobuf CONFIG REQUIRED)
