#!/usr/bin/env python3
"""
CMK-LANG per-repo evidence, wave 3 (cmake-language dive).

Fixes two bugs found in usage-requirements-in-the-wild's
.agents/research/cmake-consumable-library/scratch/consumable-library-targets/parse.py:

  BUG 1 (bracket comments): the old strip_comment() only stripped '#'-to-
  end-of-line comments, per physical line. A bracket comment -- '#[[ ... ]]'
  or '#[=[ ... ]=]', which can span many lines and is not terminated by a
  newline -- was left completely untouched, so its content (which can
  contain '(' ')' '"' '#' and CMake-call-shaped text) leaked into the
  "cleaned" text fed to the call extractor.

  BUG 2 (paren balancing ignores quoted strings): the old extract_calls()
  balanced parens by counting every literal '(' and ')' in the text between
  a call name and its close, with no notion of "this paren is inside a
  quoted argument". A quoted argument containing an unbalanced '(' or ')'
  (e.g. message("note: see foo(bar)")  -- fine, that one balances -- or
  message("unbalanced (")) desyncs the depth counter, either closing the
  call early (truncating real arguments) or running past the real close
  and swallowing the following statement(s) into "args_raw".

  Fix: a single whole-text pass (clean_text) that tracks quote state across
  the *entire file*, not per physical line (a side benefit: it also stops
  resetting quote-state at every newline, so a quoted argument that
  legitimately spans multiple lines -- cmake-language.7.rst "Quoted
  Argument" explicitly allows this -- no longer desyncs comment-stripping
  either). extract_calls() then re-tracks the same quote state (comments
  are already gone by then) while balancing parens, and additionally skips
  bracket-argument spans ('[[...]]' / '[=[...]=]') for the same reason --
  the two named bugs are quote- and bracket-comment-shaped instances of one
  root cause: the old code had no notion of "this run of the source is one
  opaque cmake-language token", full stop.

CMK-LANG counts produced:
  M-C-03  unquoted ${var} in if()/elseif()/while() comparisons; bare
          foreach(x ${list})
  M-C-04  macro() definitions, flagged by body shape (return(), ARGN
          re-expansion, set() with no PARENT_SCOPE) that would behave
          differently as a function
  M-C-06  cmake_parse_arguments() ARGN-form vs PARSE_ARGV-form, and whether
          the ARGN form's caller checks UNPARSED_ARGUMENTS /
          KEYWORDS_MISSING_VALUES
  M-C-08  hand-joined "a;b" list literals in set(); separate_arguments() use
  M-C-09  option() names without a project prefix; user variables named
          CMAKE_*

Exclusions (reported separately, never mixed into the main counts):
  - Kitware__CMake/Tests/**, Kitware__CMake/Help/**
  - any path component: contrib, third_party, third-party, deps, _deps,
    vendor, external, extern (vendored trees)
  - any file whose first 40 lines contain a generated-file banner

NEVER pipes into `grep -q` under pipefail (wave-1's SIGPIPE trap) -- single
Python process, no shell pipeline touches the corpus walk.
"""
import json
import os
import re
import sys
from collections import defaultdict

CORPUS = "/home/mherwig/.cache/research-lang/exemplars/cmake"
OUT_DIR = "/home/mherwig/.cache/cmake-measure-scratch/cmake-language"

VENDORED_COMPONENTS = {
    "contrib", "third_party", "third-party", "deps", "_deps", "vendor",
    "external", "extern",
}
SCAFFOLD_COMPONENTS = {
    "example", "examples", "test", "tests", "testing", "fixture",
    "fixtures", "sample", "samples",
}
GENERATED_BANNER_RE = re.compile(
    r"automatically generated|do not edit|generated by cmake|@generated|autogenerated",
    re.IGNORECASE,
)

CALL_NAME_RE = re.compile(r"\b([A-Za-z_][A-Za-z0-9_]*)\s*\(")


# ---------------------------------------------------------------------------
# The fix: whole-text, quote- and bracket-comment-aware cleaning.
# ---------------------------------------------------------------------------

def _bracket_close_end(text, pos):
    """text[pos] == '['. If it opens a bracket_open ('[' '='* '['), return
    the index just past the matching bracket_close; else None."""
    n = len(text)
    j = pos + 1
    eq = 0
    while j < n and text[j] == "=":
        eq += 1
        j += 1
    if j < n and text[j] == "[":
        close = "]" + ("=" * eq) + "]"
        end = text.find(close, j + 1)
        return (end + len(close)) if end != -1 else n
    return None


def clean_text(raw):
    """Strip line comments and bracket comments in one whole-file pass,
    quote-aware. Preserves every newline (inside a stripped comment too) so
    line numbers in the cleaned text still match the source."""
    out = []
    i = 0
    n = len(raw)
    in_quote = False
    while i < n:
        c = raw[i]
        if in_quote:
            if c == "\\":
                out.append(raw[i : i + 2])
                i += 2
                continue
            out.append(c)
            if c == '"':
                in_quote = False
            i += 1
            continue
        if c == '"':
            in_quote = True
            out.append(c)
            i += 1
            continue
        if c == "#":
            if i + 1 < n and raw[i + 1] == "[":
                bend = _bracket_close_end(raw, i + 1)
                if bend is not None:
                    out.append("\n" * raw.count("\n", i, bend))
                    i = bend
                    continue
            # line comment: drop through end of line, keep the newline itself
            nl = raw.find("\n", i)
            i = n if nl == -1 else nl
            continue
        out.append(c)
        i += 1
    return "".join(out)


def extract_calls(cleaned_text, wanted_lower):
    """Quote- and bracket-argument-aware, balanced-paren, multi-line-aware
    extraction of calls whose name (case-insensitively) is in wanted_lower.
    Returns (line_no, name_as_written, args_oneline, args_raw)."""
    out = []
    n = len(cleaned_text)
    for m in CALL_NAME_RE.finditer(cleaned_text):
        name = m.group(1)
        if name.lower() not in wanted_lower:
            continue
        start = m.end() - 1  # index of the '('
        i = start
        depth = 0
        in_quote = False
        while i < n:
            c = cleaned_text[i]
            if in_quote:
                if c == "\\":
                    i += 2
                    continue
                if c == '"':
                    in_quote = False
                i += 1
                continue
            if c == '"':
                in_quote = True
                i += 1
                continue
            if c == "[":
                bend = _bracket_close_end(cleaned_text, i)
                if bend is not None:
                    i = bend
                    continue
            if c == "(":
                depth += 1
            elif c == ")":
                depth -= 1
                if depth == 0:
                    break
            i += 1
        args_raw = cleaned_text[start + 1 : i]
        line_no = cleaned_text.count("\n", 0, m.start()) + 1
        oneline = " ".join(args_raw.split())
        out.append((line_no, name, oneline, args_raw))
    return out


# ---------------------------------------------------------------------------
# Self-test: the two bugs, on planted fixtures, old vs new.
# ---------------------------------------------------------------------------

def _old_strip_comment_per_line(line):
    out, inq, esc = [], False, False
    for ch in line:
        if esc:
            out.append(ch)
            esc = False
            continue
        if ch == "\\" and inq:
            out.append(ch)
            esc = True
            continue
        if ch == '"':
            inq = not inq
        if ch == "#" and not inq:
            break
        out.append(ch)
    return "".join(out)


def _old_clean(raw):
    return "\n".join(_old_strip_comment_per_line(l) for l in raw.split("\n"))


def _old_extract_calls(cleaned_text, wanted_lower):
    out = []
    for m in CALL_NAME_RE.finditer(cleaned_text):
        name = m.group(1)
        if name.lower() not in wanted_lower:
            continue
        start = m.end() - 1
        depth = 0
        i = start
        n = len(cleaned_text)
        while i < n:
            c = cleaned_text[i]
            if c == "(":
                depth += 1
            elif c == ")":
                depth -= 1
                if depth == 0:
                    break
            i += 1
        args_raw = cleaned_text[start + 1 : i]
        line_no = cleaned_text.count("\n", 0, m.start()) + 1
        out.append((line_no, name, " ".join(args_raw.split()), args_raw))


    return out


def demo():
    """assert-based self-check: old parser fails each fixture, new parser
    doesn't. Run standalone: python3 parse_fixed.py --demo"""
    fx_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fixtures")

    # Fixture 1: a bracket comment ahead of a real call, its content shaped
    # like a call with an unmatched paren -- if not stripped, the old parser
    # either desyncs its depth count or picks up "commands(" as a phantom call.
    f1 = open(os.path.join(fx_dir, "01_bracket_comment_simple.cmake")).read()
    # Fixture 2: a bracket comment using the #[=[ ... ]=] long form, whose
    # body contains a literal "]]" that must NOT close it early.
    f2 = open(os.path.join(fx_dir, "02_bracket_comment_equals.cmake")).read()
    # Fixture 3: a quoted argument containing an unbalanced '(' -- the old
    # depth counter never reaches 0 inside the intended call, and swallows
    # the next statement into its "args".
    f3 = open(os.path.join(fx_dir, "03_quoted_unbalanced_paren.cmake")).read()

    wanted = {"message", "set", "real_call", "should_not_see_this"}

    # --- Fixture 1 ---
    old_calls = _old_extract_calls(_old_clean(f1), wanted)
    new_calls = extract_calls(clean_text(f1), wanted)
    old_names = [c[1] for c in old_calls]
    new_names = [c[1] for c in new_calls]
    assert "should_not_see_this" in old_names, (
        "fixture 1 no longer demonstrates the bug (old parser expected to "
        "see the bracket comment's inner call name); old_names=%r" % old_names
    )
    assert "should_not_see_this" not in new_names, (
        "BUG 1 not fixed: bracket comment content leaked into a real call: %r" % new_names
    )
    assert new_names == ["real_call"], new_names

    # --- Fixture 2: matching close must use the same '=' count, and a
    #     shorter close inside the comment must not end it early.
    new_calls2 = extract_calls(clean_text(f2), wanted)
    new_names2 = [c[1] for c in new_calls2]
    assert new_names2 == ["real_call"], (
        "BUG 1 (equals-form) not fixed, or premature-close bug: %r" % new_names2
    )

    # --- Fixture 3 ---
    old_calls3 = _old_extract_calls(_old_clean(f3), wanted)
    new_calls3 = extract_calls(clean_text(f3), wanted)
    old_args = [c[2] for c in old_calls3 if c[1] == "message"]
    new_args = [c[2] for c in new_calls3]
    # Old parser: depth never returns to 0 inside message(...)'s real close,
    # so it either keeps consuming (swallowing set(...) too) or its args
    # string contains the *next* statement's tokens.
    assert any("REAL_MARKER" in a for a in old_args) or len(old_calls3) < 2, (
        "fixture 3 no longer demonstrates the bug; old_calls3=%r" % (old_calls3,)
    )
    new_names3 = [c[1] for c in new_calls3]
    assert new_names3 == ["message", "set"], (
        "BUG 2 not fixed: quoted unbalanced paren desynced the new parser too: %r"
        % new_names3
    )
    assert "REAL_MARKER" not in new_calls3[0][2], (
        "BUG 2 not fixed: message()'s args leaked into the following set(): %r"
        % (new_calls3[0][2],)
    )

    print("demo: all 3 fixtures pass (old parser fails each one, new parser fixes each one)")


# ---------------------------------------------------------------------------
# Corpus walk
# ---------------------------------------------------------------------------

def is_vendored(relpath):
    parts = relpath.split(os.sep)
    return any(p in VENDORED_COMPONENTS for p in parts)


def is_scaffold(relpath):
    parts = [p.lower() for p in relpath.split(os.sep)]
    return any(p in SCAFFOLD_COMPONENTS for p in parts)


def is_kitware_excluded(repo, relpath):
    if repo != "Kitware__CMake":
        return False
    return relpath.startswith("Tests" + os.sep) or relpath.startswith("Help" + os.sep)


def iter_files():
    for repo in sorted(os.listdir(CORPUS)):
        rd = os.path.join(CORPUS, repo)
        if not os.path.isdir(os.path.join(rd, ".git")):
            continue
        for root, dirs, files in os.walk(rd):
            if os.sep + ".git" in root or root.endswith(os.sep + ".git"):
                dirs[:] = []
                continue
            for f in files:
                if f == "CMakeLists.txt" or f.endswith(".cmake"):
                    full = os.path.join(root, f)
                    rel = os.path.relpath(full, rd)
                    yield repo, rel, full


UNQUOTED_VAR_COMPARE_RE = re.compile(
    r"(?<![A-Za-z0-9_}])\$\{[A-Za-z_][A-Za-z0-9_]*\}(?![A-Za-z0-9_{])"
    r'[^"]{0,40}?\b(STREQUAL|MATCHES|EQUAL|VERSION_(LESS|GREATER|EQUAL)[A-Z_]*)\b'
)
QUOTED_BEFORE_RE = re.compile(r'"\s*\$\{[A-Za-z_][A-Za-z0-9_]*\}\s*"')
BARE_FOREACH_RE = re.compile(r"^\s*[A-Za-z_][A-Za-z0-9_]*\s+\$\{[A-Za-z_][A-Za-z0-9_]*\}\s*$")
HAND_JOINED_LIST_RE = re.compile(r'"[^"\n]*;[^"\n]*"')
PARSE_ARGV_RE = re.compile(r"^\s*PARSE_ARGV\b")

WANTED = {
    "if", "elseif", "while", "foreach", "macro", "endmacro", "function",
    "endfunction", "option", "cmake_parse_arguments", "set", "separate_arguments",
}


def main():
    if len(sys.argv) > 1 and sys.argv[1] == "--demo":
        demo()
        return

    per_repo = defaultdict(lambda: defaultdict(int))
    examples = defaultdict(list)
    EXAMPLE_CAP = 60

    def add_example(axis, repo, relpath, line, snippet):
        if len(examples[axis]) < EXAMPLE_CAP:
            examples[axis].append(f"{repo}:{relpath}:{line}: {snippet}")

    file_count = defaultdict(int)
    kitware_excluded_count = 0
    generated_file_count = defaultdict(int)
    option_names = defaultdict(set)

    for repo, relpath, full in iter_files():
        if is_kitware_excluded(repo, relpath):
            kitware_excluded_count += 1
            continue
        vendored = is_vendored(relpath)
        scaffold = is_scaffold(relpath)
        try:
            with open(full, "r", errors="replace") as fh:
                raw = fh.read()
        except OSError:
            continue

        head = "\n".join(raw.split("\n")[:40])
        if GENERATED_BANNER_RE.search(head):
            generated_file_count[repo] += 1
            continue

        bucket = "vendored" if vendored else ("scaffold" if scaffold else "core")
        file_count[repo] += 1

        cleaned = clean_text(raw)
        calls = extract_calls(cleaned, WANTED)

        # ---- macro bodies (M-C-04): text span from macro( to its matching
        # endmacro(, found positionally (macros don't nest in the corpus in
        # a way that defeats a simple next-endmacro-after-this-macro scan;
        # verified by hand on the sample below).
        macro_starts = [(ln, oneline) for (ln, nm, oneline, raw_a) in calls if nm.lower() == "macro"]
        endmacro_lines = sorted(ln for (ln, nm, _, _) in calls if nm.lower() == "endmacro")
        lines_arr = cleaned.split("\n")
        for (mstart_line, monel) in macro_starts:
            per_repo[(repo, bucket)]["macro_total"] += 1
            close = next((e for e in endmacro_lines if e >= mstart_line), None)
            body = "\n".join(lines_arr[mstart_line - 1 : close]) if close else "\n".join(lines_arr[mstart_line - 1 :])
            has_return = bool(re.search(r"\breturn\s*\(", body))
            has_argn = bool(re.search(r"\$\{ARGN\}|\bARGN\b", body))
            has_bare_set_novar = bool(
                re.search(r"\bset\s*\(\s*[A-Za-z_][A-Za-z0-9_]*\s", body)
                and not re.search(r"PARENT_SCOPE", body)
            )
            flags = []
            if has_return:
                flags.append("return")
                per_repo[(repo, bucket)]["macro_with_return"] += 1
            if has_argn:
                flags.append("argn")
                per_repo[(repo, bucket)]["macro_with_argn"] += 1
            if has_bare_set_novar:
                flags.append("bare_set")
            if flags:
                per_repo[(repo, bucket)]["macro_flagged_any"] += 1
                name_m = re.match(r"^\s*([A-Za-z_][A-Za-z0-9_]*)", monel)
                mname = name_m.group(1) if name_m else "?"
                add_example(
                    "M-C-04-flagged", repo, relpath, mstart_line,
                    f"macro({mname}) [{'+'.join(flags)}]",
                )

        for line_no, name, oneline, raw_args in calls:
            lname = name.lower()

            if lname in ("if", "elseif", "while"):
                per_repo[(repo, bucket)][f"{lname}_total"] += 1
                stripped_quoted = QUOTED_BEFORE_RE.sub('"Q"', raw_args)
                if UNQUOTED_VAR_COMPARE_RE.search(stripped_quoted):
                    per_repo[(repo, bucket)]["unquoted_if_compare"] += 1
                    add_example("M-C-03-unquoted-if", repo, relpath, line_no, f"{lname}({oneline[:100]})")

            elif lname == "foreach":
                per_repo[(repo, bucket)]["foreach_total"] += 1
                if BARE_FOREACH_RE.match(oneline):
                    per_repo[(repo, bucket)]["foreach_bare"] += 1
                    add_example("M-C-03-bare-foreach", repo, relpath, line_no, f"foreach({oneline[:100]})")

            elif lname == "option":
                toks = oneline.split()
                if toks:
                    optname = toks[0].strip('"')
                    per_repo[(repo, bucket)]["option_total"] += 1
                    option_names[(repo, bucket)].add(optname)
                    if optname.upper().startswith("CMAKE_"):
                        per_repo[(repo, bucket)]["option_cmake_prefixed"] += 1
                        add_example("M-C-09-cmake-prefixed", repo, relpath, line_no, f"option({oneline[:100]})")

            elif lname == "cmake_parse_arguments":
                per_repo[(repo, bucket)]["cpa_total"] += 1
                is_parse_argv = bool(PARSE_ARGV_RE.match(raw_args.strip()))
                if is_parse_argv:
                    per_repo[(repo, bucket)]["cpa_parse_argv"] += 1
                    prefix_m = re.match(r"^\s*PARSE_ARGV\s+\d+\s+([A-Za-z_][A-Za-z0-9_]*)", raw_args)
                else:
                    per_repo[(repo, bucket)]["cpa_argn_form"] += 1
                    prefix_m = re.match(r"^\s*\"?([A-Za-z_][A-Za-z0-9_]*)\"?", raw_args)
                prefix = prefix_m.group(1) if prefix_m else None
                # look at the next ~60 lines (or to end of enclosing function/
                # macro) for the two named checks
                window = "\n".join(lines_arr[line_no - 1 : line_no + 59])
                checks_unparsed = bool(prefix and re.search(rf"\b{re.escape(prefix)}_UNPARSED_ARGUMENTS\b", window))
                checks_missing = bool(prefix and re.search(rf"\b{re.escape(prefix)}_KEYWORDS_MISSING_VALUES\b", window))
                if not is_parse_argv:
                    if not checks_unparsed:
                        per_repo[(repo, bucket)]["cpa_argn_no_unparsed_check"] += 1
                    if not checks_missing:
                        per_repo[(repo, bucket)]["cpa_argn_no_missing_check"] += 1
                    if not (checks_unparsed and checks_missing):
                        add_example(
                            "M-C-06-argn-unchecked", repo, relpath, line_no,
                            f"cmake_parse_arguments({oneline[:80]}) unparsed={checks_unparsed} missing={checks_missing}",
                        )

            elif lname == "set":
                if HAND_JOINED_LIST_RE.search(raw_args):
                    per_repo[(repo, bucket)]["hand_joined_list"] += 1
                    add_example("M-C-08-hand-joined", repo, relpath, line_no, f"set({oneline[:100]})")

            elif lname == "separate_arguments":
                per_repo[(repo, bucket)]["separate_arguments_use"] += 1
                add_example("M-C-08-separate-arguments", repo, relpath, line_no, f"separate_arguments({oneline[:100]})")

    for (repo, bucket), names in option_names.items():
        d = per_repo[(repo, bucket)]
        pref_count = defaultdict(int)
        for nm in names:
            if "_" in nm:
                pref_count[nm.split("_")[0].upper()] += 1
        if pref_count:
            pfx, cnt = max(pref_count.items(), key=lambda kv: kv[1])
        else:
            pfx, cnt = None, 0
        d["option_distinct_names"] = len(names)
        d["option_dominant_prefix"] = pfx or ""
        d["option_dominant_prefix_count"] = cnt
        unprefixed = sum(1 for nm in names if not (pfx and nm.upper().startswith(pfx + "_")))
        d["option_unprefixed_estimate"] = unprefixed

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(os.path.join(OUT_DIR, "per_repo_counts.json"), "w") as f:
        json.dump({f"{r}|{b}": dict(d) for (r, b), d in per_repo.items()}, f, indent=1, sort_keys=True)
    with open(os.path.join(OUT_DIR, "examples.json"), "w") as f:
        json.dump(examples, f, indent=1, sort_keys=True)
    with open(os.path.join(OUT_DIR, "exclusions_summary.json"), "w") as f:
        json.dump(
            {
                "kitware_tests_help_files_excluded": kitware_excluded_count,
                "generated_files_excluded_per_repo": dict(generated_file_count),
                "firstparty_plus_vendored_files_scanned_by_repo": dict(file_count),
            },
            f,
            indent=1,
            sort_keys=True,
        )
    print("done", file=sys.stderr)


if __name__ == "__main__":
    main()
