#!/usr/bin/env python3
"""Compose a set mark: the ocx base plus a badge disc carrying a set glyph.

    scripts/make-mark.py rust assets/glyphs/rust.svg
    scripts/make-mark.py python assets/glyphs/python.svg --disc '#0B2B45' --ink '#FFD343'

Writes assets/lore-<set>.svg. The base comes from assets/lore.svg, so the ocx
mark is stored once and every set mark re-derives from it.

ponytail: no config file, no build system — the set list lives in publish.toml
and this runs per set. Add a sets manifest if the count ever makes that tedious.
"""

import argparse
import re
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BOX = 128  # base mark viewBox
DISC = (99, 99, 25)  # badge centre and radius — arcana's hex geometry
GLYPH_SPAN = 34  # glyph width inside the disc


def body_of(svg: str) -> str:
    """Markup between the <svg> tags."""
    return svg[svg.index(">", svg.index("<svg")) + 1 : svg.rindex("</svg>")].strip()


def viewbox_of(svg: str) -> tuple[float, float, float, float]:
    """The glyph's own coordinate system, from viewBox or width/height."""
    m = re.search(r'viewBox="([^"]+)"', svg)
    if m:
        x, y, w, h = (float(v) for v in m.group(1).replace(",", " ").split())
        return x, y, w, h
    w = re.search(r'\bwidth="([\d.]+)', svg)
    h = re.search(r'\bheight="([\d.]+)', svg)
    if not (w and h):
        sys.exit("glyph has neither a viewBox nor numeric width/height")
    return 0.0, 0.0, float(w.group(1)), float(h.group(1))


def namespace_ids(markup: str, prefix: str) -> str:
    """Prefix the glyph's own ids so they cannot collide with the base's."""
    ids = set(re.findall(r'\bid="([^"]+)"', markup))
    for i in sorted(ids, key=len, reverse=True):
        markup = markup.replace(f'id="{i}"', f'id="{prefix}-{i}"')
        markup = markup.replace(f"url(#{i})", f"url(#{prefix}-{i})")
        markup = markup.replace(f'href="#{i}"', f'href="#{prefix}-{i}"')
    return markup


BLACK = re.compile(r'\b(fill|stroke)="(#000|#000000|black)"', re.IGNORECASE)


def repaint_black(markup: str, colour: str) -> str:
    """Retarget hard-coded black paint on the glyph's own elements.

    An element's own `fill`/`stroke` beats anything inherited from the wrapper,
    so a glyph that paints itself black ignores a paint override entirely. The
    Rust logo is one path with `stroke="#000"`: overriding only `fill` left the
    gear teeth black. Scoped to black on purpose — a full-colour logo asked to
    be repainted should keep its own colours.
    """
    return BLACK.sub(lambda m: f'{m.group(1)}="{colour}"', markup)


@dataclass(frozen=True)
class Style:
    """How the badge is painted. Grouped because these five travel together.

    Eight positional parameters is how a `span`/`fill` transposition reaches
    a call site unnoticed; keeping them in one value makes each one named at
    every call.
    """

    disc: str
    ink: str
    span: float = GLYPH_SPAN
    fill: str | None = None
    stroke: str | None = None


def compose(name: str, glyph_svg: str, base_svg: str, style: Style) -> str:
    disc, ink, span = style.disc, style.ink, style.span
    fill, stroke = style.fill, style.stroke
    cx, cy, r = DISC
    gx, gy, gw, gh = viewbox_of(glyph_svg)
    scale = span / max(gw, gh)
    # Centre the glyph's own box on the disc centre. Subtract the viewBox
    # origin: it is 0 0 for most icon sets, but not all (the Python logo starts
    # at 0.21 -0.077), and ignoring it shifts the glyph off centre.
    tx = cx - (gw * scale) / 2 - gx * scale
    ty = cy - (gh * scale) / 2 - gy * scale
    glyph = namespace_ids(body_of(glyph_svg), name)
    paint_colour = stroke or fill
    if paint_colour:
        glyph = repaint_black(glyph, paint_colour)
    # A monochrome glyph (simple-icons and friends) carries no fill and would
    # render black; a full-colour logo brings its own and ignores this.
    # Stroke sets (lucide) put fill/stroke on the <svg> element itself, which
    # is exactly the tag dropped on the way in — so restate them on the wrapper.
    if stroke:
        paint = (
            f' fill="none" stroke="{stroke}" stroke-width="2"'
            ' stroke-linecap="round" stroke-linejoin="round"'
        )
    else:
        paint = f' fill="{fill}"' if fill else ""

    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {BOX} {BOX}" '
        f'width="{BOX}" height="{BOX}">\n'
        f"  {body_of(base_svg)}\n"
        f"  <!-- {name} badge: set glyph on the bottom-right disc. Generated by\n"
        f"       scripts/make-mark.py — edit the glyph or the base, not this file. -->\n"
        f'  <circle cx="{cx}" cy="{cy}" r="{r}" fill="{disc}" stroke="{ink}" stroke-width="2.5"/>\n'
        f'  <g{paint} transform="translate({tx:.4g} {ty:.4g}) scale({scale:.4g})">{glyph}</g>\n'
        "</svg>\n"
    )


def expect(condition: bool, what: str) -> None:
    """`assert` is stripped by `python -O`; a self-test must not be."""
    if not condition:
        raise SystemExit(f"selftest: {what}")


def selftest() -> None:
    base = '<svg viewBox="0 0 128 128"><rect id="b" width="1" height="1"/></svg>'
    glyph = '<svg viewBox="0 0 10 20"><path id="b" d="M0 0h1"/></svg>'
    plain = Style(disc="#FFF", ink="#000")
    out = compose("t", glyph, base, plain)
    ET.fromstring(out)  # noqa: S314 - input is composed two lines above, not untrusted
    expect('id="t-b"' in out and 'id="b"' in out, "glyph ids namespaced, base's left alone")
    tx, ty, s = _transform_of(out)
    expect(abs(s * 20 - GLYPH_SPAN) < 1e-6, "longest side fills the span")
    expect(abs(tx + s * 10 / 2 - DISC[0]) < 1e-6, "centred on the disc horizontally")
    expect(abs(ty + s * 20 / 2 - DISC[1]) < 1e-6, "centred on the disc vertically")

    # A viewBox that does not start at the origin still lands centred.
    off = '<svg viewBox="5 -3 10 20"><path d="M0 0h1"/></svg>'
    tx, ty, s = _transform_of(compose("t", off, base, plain))
    expect(abs(tx + s * (5 + 10 / 2) - DISC[0]) < 1e-6, "offset viewBox centred horizontally")
    expect(abs(ty + s * (-3 + 20 / 2) - DISC[1]) < 1e-6, "offset viewBox centred vertically")

    # Stroke glyphs must not be handed a fill, or lucide icons render solid.
    stroked = Style(disc="#FFF", ink="#000", stroke="#123456")
    expect('fill="none"' in compose("t", glyph, base, stroked), "stroke glyphs get no fill")

    # A glyph that paints itself black wins over the wrapper, so an explicit
    # paint has to reach inside it (the Rust logo's stroke="#000" gear teeth).
    selfpainted = '<svg viewBox="0 0 10 10"><path stroke="#000" fill="black" d="M0 0h1"/></svg>'
    filled = Style(disc="#FFF", ink="#000", fill="#ABCDEF")
    out = compose("t", selfpainted, base, filled)
    expect(
        'stroke="#ABCDEF"' in out and 'fill="#ABCDEF"' in out and "#000" not in out.split("<g")[-1],
        "an explicit paint reaches inside a self-painted glyph",
    )
    # ...but only black. A full-colour logo keeps its own paint.
    colour = '<svg viewBox="0 0 10 10"><path fill="#FFD43B" d="M0 0h1"/></svg>'
    expect("#FFD43B" in compose("t", colour, base, filled), "a full-colour logo keeps its paint")
    print("selftest ok")


def _transform_of(svg: str) -> tuple[float, float, float]:
    m = re.search(r"translate\((-?[\d.]+) (-?[\d.]+)\) scale\(([\d.]+)\)", svg)
    return tuple(float(v) for v in m.groups())


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("name", nargs="?", help="set name, e.g. rust")
    p.add_argument("glyph", nargs="?", help="path to the set's glyph SVG")
    p.add_argument("--disc", default="#FFF3F0", help="disc fill (default: cream)")
    p.add_argument("--ink", default="#3A1008", help="disc stroke (default: deep coral)")
    # Scaling off the viewBox means a glyph with generous padding lands small.
    # Nudge per glyph rather than parsing paths for a real content bbox.
    # A square glyph needs a smaller span than a round one: its corners sit at
    # span * 0.707 from the centre, so 34 already touches the r=25 disc.
    p.add_argument(
        "--span",
        type=float,
        default=GLYPH_SPAN,
        help=f"glyph width across its viewBox (default: {GLYPH_SPAN})",
    )
    p.add_argument("--glyph-fill", help="fill for a monochrome glyph that carries none")
    p.add_argument("--glyph-stroke", help="stroke colour for a stroke-drawn glyph (lucide et al)")
    p.add_argument("--selftest", action="store_true")
    a = p.parse_args()

    if a.selftest:
        selftest()
        return
    if not (a.name and a.glyph):
        p.error("name and glyph are required")

    out = ROOT / "assets" / f"lore-{a.name}.svg"
    composed = compose(
        a.name,
        Path(a.glyph).read_text(),
        (ROOT / "assets" / "lore.svg").read_text(),
        Style(
            disc=a.disc,
            ink=a.ink,
            span=a.span,
            fill=a.glyph_fill,
            stroke=a.glyph_stroke,
        ),
    )
    # A hand-authored glyph can be malformed in ways only a parser catches — a
    # literal `--` inside an XML comment, say. Fail here, not at render time.
    try:
        # `composed` is built by this script from a local glyph and the
        # committed base mark — a well-formedness probe on our own output, not
        # a parse of anything a stranger sent.
        ET.fromstring(composed)  # noqa: S314
    except ET.ParseError as e:
        sys.exit(f"{a.glyph}: composed mark is not well-formed XML: {e}")
    out.write_text(composed)
    print(f"wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
