#!/usr/bin/env python3
"""Compose a set mark: the ocx base plus a badge disc carrying a set glyph.

    scripts/make-mark.py rust assets/glyphs/rust.svg
    scripts/make-mark.py python assets/glyphs/python.svg --disc '#0B2B45' --ink '#FFD343'

Writes assets/lore-<set>.svg. The base comes from assets/lore.svg, so the ocx
mark is stored once and every set mark re-derives from it.

ponytail: no config file, no build system — the set list lives in publish.toml
and this runs per set. Add a sets manifest if the count ever makes that tedious.
"""

import argparse
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BOX = 128            # base mark viewBox
DISC = (99, 99, 25)  # badge centre and radius — arcana's hex geometry
GLYPH_SPAN = 34      # glyph width inside the disc


def body_of(svg: str) -> str:
    """Markup between the <svg> tags."""
    return svg[svg.index(">", svg.index("<svg")) + 1 : svg.rindex("</svg>")].strip()


def viewbox_of(svg: str) -> tuple[float, float, float, float]:
    """The glyph's own coordinate system, from viewBox or width/height."""
    m = re.search(r'viewBox="([^"]+)"', svg)
    if m:
        x, y, w, h = (float(v) for v in m.group(1).replace(",", " ").split())
        return x, y, w, h
    w = re.search(r'\bwidth="([\d.]+)', svg)
    h = re.search(r'\bheight="([\d.]+)', svg)
    if not (w and h):
        sys.exit("glyph has neither a viewBox nor numeric width/height")
    return 0.0, 0.0, float(w.group(1)), float(h.group(1))


def namespace_ids(markup: str, prefix: str) -> str:
    """Prefix the glyph's own ids so they cannot collide with the base's."""
    ids = set(re.findall(r'\bid="([^"]+)"', markup))
    for i in sorted(ids, key=len, reverse=True):
        markup = markup.replace(f'id="{i}"', f'id="{prefix}-{i}"')
        markup = markup.replace(f"url(#{i})", f"url(#{prefix}-{i})")
        markup = markup.replace(f'href="#{i}"', f'href="#{prefix}-{i}"')
    return markup


def compose(name: str, glyph_svg: str, disc: str, ink: str, base_svg: str,
            span: float = GLYPH_SPAN, fill: str | None = None) -> str:
    cx, cy, r = DISC
    _, _, gw, gh = viewbox_of(glyph_svg)
    scale = span / max(gw, gh)
    # centre the glyph's own box on the disc centre
    tx = cx - (gw * scale) / 2
    ty = cy - (gh * scale) / 2
    glyph = namespace_ids(body_of(glyph_svg), name)
    # A monochrome glyph (simple-icons and friends) carries no fill and would
    # render black; a full-colour logo brings its own and ignores this.
    paint = f' fill="{fill}"' if fill else ""

    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {BOX} {BOX}" '
        f'width="{BOX}" height="{BOX}">\n'
        f"  {body_of(base_svg)}\n"
        f"  <!-- {name} badge: set glyph on the bottom-right disc. Generated by\n"
        f"       scripts/make-mark.py — edit the glyph or the base, not this file. -->\n"
        f'  <circle cx="{cx}" cy="{cy}" r="{r}" fill="{disc}" stroke="{ink}" stroke-width="2.5"/>\n'
        f'  <g{paint} transform="translate({tx:.4g} {ty:.4g}) scale({scale:.4g})">{glyph}</g>\n'
        "</svg>\n"
    )


def selftest() -> None:
    base = '<svg viewBox="0 0 128 128"><rect id="b" width="1" height="1"/></svg>'
    glyph = '<svg viewBox="0 0 10 20"><path id="b" d="M0 0h1"/></svg>'
    out = compose("t", glyph, "#FFF", "#000", base)
    ET.fromstring(out)                              # well-formed
    assert 'id="t-b"' in out and 'id="b"' in out    # glyph ids namespaced, base's left alone
    m = re.search(r"translate\(([\d.]+) ([\d.]+)\) scale\(([\d.]+)\)", out)
    tx, ty, s = (float(v) for v in m.groups())
    assert abs(s * 20 - GLYPH_SPAN) < 1e-6          # longest side fills the span
    assert abs(tx + s * 10 / 2 - DISC[0]) < 1e-6    # centred on the disc
    assert abs(ty + s * 20 / 2 - DISC[1]) < 1e-6
    print("selftest ok")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("name", nargs="?", help="set name, e.g. rust")
    p.add_argument("glyph", nargs="?", help="path to the set's glyph SVG")
    p.add_argument("--disc", default="#FFF3F0", help="disc fill (default: cream)")
    p.add_argument("--ink", default="#3A1008", help="disc stroke (default: deep coral)")
    # Scaling off the viewBox means a glyph with generous padding lands small.
    # Nudge per glyph rather than parsing paths for a real content bbox.
    p.add_argument("--span", type=float, default=GLYPH_SPAN,
                   help=f"glyph width across its viewBox (default: {GLYPH_SPAN})")
    p.add_argument("--glyph-fill", help="fill for a monochrome glyph that carries none")
    p.add_argument("--selftest", action="store_true")
    a = p.parse_args()

    if a.selftest:
        return selftest()
    if not (a.name and a.glyph):
        p.error("name and glyph are required")

    out = ROOT / "assets" / f"lore-{a.name}.svg"
    composed = (
        compose(
            a.name,
            Path(a.glyph).read_text(),
            a.disc,
            a.ink,
            (ROOT / "assets" / "lore.svg").read_text(),
            a.span,
            a.glyph_fill,
        )
    )
    # A hand-authored glyph can be malformed in ways only a parser catches — a
    # literal `--` inside an XML comment, say. Fail here, not at render time.
    try:
        ET.fromstring(composed)
    except ET.ParseError as e:
        sys.exit(f"{a.glyph}: composed mark is not well-formed XML: {e}")
    out.write_text(composed)
    print(f"wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
