cmake_minimum_required(VERSION 3.25)
if(MODE STREQUAL "before")
  set(VCPKG_TARGET_TRIPLET arm64-linux)
endif()
project(p NONE)
if(MODE STREQUAL "after")
  set(VCPKG_TARGET_TRIPLET arm64-linux)
endif()
find_package(foo CONFIG REQUIRED)
message(STATUS "MODE=${MODE} found foo from triplet ${FOO_TRIPLET}")
