cmake_minimum_required(VERSION 3.25...4.4)
project(bsls C)
set(BUILD_SHARED_LIBS ON)
set(CMAKE_POLICY_DEFAULT_CMP0077 NEW)
add_subdirectory(../dep312 dep312)
unset(CMAKE_POLICY_DEFAULT_CMP0077)
unset(BUILD_SHARED_LIBS)
add_subdirectory(../depB312 depB312)
get_target_property(_a depA TYPE)
get_target_property(_b depB TYPE)
message(STATUS "DEPA_TYPE=${_a} DEPB_TYPE=${_b}")
