export const meta = {
  name: 'go-author',
  description: 'Go research program phase 7: opus drafters write the depth files of each rule from the consolidations, pipelined into one index drafter per rule; skills and the Bazel-Go depth file draft alongside',
  phases: [
    { title: 'Depth', detail: 'one opus drafter per depth file', model: 'opus' },
    { title: 'Index', detail: 'one opus drafter per rule index, after its depth files exist', model: 'opus' },
    { title: 'Standalone', detail: 'skills and the bazel-quality Go depth file', model: 'opus' },
  ],
}

// Generated by mkauthor.py. PLAN = { rules: [{ rule, glob_list, core_family, index_sources, depth: [{ file, family, sources, task_hint }] }], standalone: [{ kind, path, sources, brief }] }
const ROOT = '/home/mherwig/dev/grimoire-lore/.agents/worktrees/go'
const RESEARCH = ROOT + '/.agents/research'
const DATE = '2026-09-26'
const PLAN = {
 "rules": [
  {
   "rule": "go-quality",
   "glob_list": [
    "**/*.go"
   ],
   "core_family": "GO-CORE",
   "index_sources": [
    "go-gates.md",
    "go-topic-map.md",
    "go-frame.md"
   ],
   "depth": [
    {
     "file": "language.md",
     "family": "GO-LANG",
     "sources": [
      "go-language.md"
     ],
     "task_hint": "writing any new Go against the module's go line, choosing an idiom that changed between releases, designing a generic function or an iterator, touching JSON, maps, time, runes or randomness",
     "extra": "Apply notes N-8 (GO-LANG-04's durable check is the oldstable build leg, and golangci govet and nogo are blind to the json/v2 case) and 'Wave 4 landed' contradiction 7 (fix the inverted nogreenteagc example; use C9's watched grep) and contradiction 1 (x/exp/constraints is the depguard entry GO-LANG-22 adds; cite GO-MOD-08, do not restate the list)."
    },
    {
     "file": "errors.md",
     "family": "GO-ERR",
     "sources": [
      "go-errors.md"
     ],
     "task_hint": "returning, wrapping, matching or exposing an error, panicking, exiting, or closing a writable resource"
    },
    {
     "file": "concurrency.md",
     "family": "GO-CONC",
     "sources": [
      "go-concurrency.md"
     ],
     "task_hint": "starting a goroutine, fanning out work, passing or storing a context, cancelling, or sharing state across goroutines"
    },
    {
     "file": "api-design.md",
     "family": "GO-API",
     "sources": [
      "go-api.md"
     ],
     "task_hint": "adding or changing an exported identifier, laying out packages, choosing options versus a config struct, writing doc comments, or building the SDK surface that wraps a CLI"
    },
    {
     "file": "testing.md",
     "family": "GO-TEST",
     "sources": [
      "go-testing.md"
     ],
     "task_hint": "writing or reviewing a test, a fuzz target, a benchmark, a golden file, a helper process, or a coverage gate"
    },
    {
     "file": "cli-contract.md",
     "family": "GO-CLI",
     "sources": [
      "go-cli.md"
     ],
     "task_hint": "writing a main package, choosing an exit code, wiring cobra, handling a signal or a broken pipe, or writing to stdout, stderr or a terminal"
    },
    {
     "file": "io.md",
     "family": "GO-IO",
     "sources": [
      "go-io.md"
     ],
     "task_hint": "writing or replacing a file on disk, confining paths, extracting an archive, or starting and reaping a subprocess",
     "extra": "Apply note N-6: GO-IO-18 is retired (duplicate of GO-NET-14); write one line saying so with the pointer to GO-NET-14 in network.md by family name, and never reuse the number."
    },
    {
     "file": "network.md",
     "family": "GO-NET",
     "sources": [
      "go-network.md"
     ],
     "task_hint": "making an HTTP request, configuring a client or server, retrying, streaming a body, or talking to an OCI registry",
     "extra": "Apply note N-7 (GO-NET-06 wiring on go-containerregistry, marked 'wiring by source read, not fixture-watched') and N-6 (GO-IO-18 is retired; blob staging lives here as GO-NET-14)."
    },
    {
     "file": "security.md",
     "family": "GO-SEC",
     "sources": [
      "go-security.md"
     ],
     "task_hint": "generating a secret or token, configuring TLS, handling credentials, rendering templates, using unsafe, or bounding untrusted input"
    },
    {
     "file": "observability.md",
     "family": "GO-OBS",
     "sources": [
      "go-observability.md"
     ],
     "task_hint": "logging, exposing pprof or metrics, tuning GOMAXPROCS or GOMEMLIMIT, diagnosing a hang or leak, or making or judging a performance claim"
    }
   ]
  },
  {
   "rule": "go-modules",
   "glob_list": [
    "**/go.mod",
    "**/go.sum",
    "**/go.work",
    "**/go.work.sum",
    "**/.golangci.*",
    "**/*golangci*.yml",
    "**/*golangci*.yaml",
    "**/.goreleaser.*",
    "**/goreleaser*.yml",
    "**/goreleaser*.yaml",
    "**/.config/goreleaser.*",
    "**/.ko.yaml",
    "**/staticcheck.conf"
   ],
   "core_family": "GO-MOD",
   "index_sources": [
    "go-modules.md",
    "go-gates.md"
   ],
   "depth": [
    {
     "file": "gates.md",
     "family": "GO-GATE",
     "sources": [
      "go-gates.md"
     ],
     "task_hint": "writing or changing the CI gate, a golangci-lint config, a staticcheck config, the go vet or govulncheck step, or adding a linter",
     "extra": "Apply 'Wave 4 landed' contradiction 1 before copying any config: GO-MOD-08's depguard superseded list is 13 entries (its 11, plus go.uber.org/automaxprocs per GO-OBS-06, plus golang.org/x/exp/constraints per GO-LANG-22). Re-quote it into all three config files, then re-run 'golangci-lint config verify' on each copy under your fixture dir and the GO-GATE-22 superset check, and record the result. Apply contradiction 2: GO-GATE-01 gains conditional step 10 (pinned gopls check for the yield analyzer, only where func(yield func( appears, stable leg only). The three complete config files ship as REAL FILES you also write: rules/go-modules/golangci/baseline.golangci.yml, rules/go-modules/golangci/cli.golangci.yml and rules/go-modules/golangci/lib-sdk.golangci.yml (each a complete v2 file with a header comment naming the GO-GATE IDs it implements and 'measured 2026-09-26, golangci-lint v2.14.0'). gates.md links each file by relative path, explains when to copy which (GO-GATE-18/22/23), and quotes only the few lines a reader must see inline; N-4's 'config YAML appears only in gates.md' is satisfied by these three files being gates.md's own attachments. Before returning, run '/home/mherwig/.cache/research-lang/go-tools/run.sh golangci-lint config verify --config <file>' on each of the three shipped files (from a scratch module dir under your fixture dir) and require exit 0; record the three exit codes in your receipt notes. Keep gates.md under 300 lines."
    },
    {
     "file": "release.md",
     "family": "GO-REL",
     "sources": [
      "go-release.md"
     ],
     "task_hint": "building a release binary, stamping a version, writing a goreleaser or ko config, signing or attesting assets, or tagging a module version",
     "extra": "Apply note N-6: GO-REL-13 is dropped (GO-API-10 wins); keep a one-line citation that says GO-REL-13 is retired in favour of GO-API-10, and never reuse the number."
    }
   ],
   "extra": "The go-modules index OWNS GO-MOD-01..18 (note N-3): its rule tables live in the index itself, not in a depth file, so the index is the GO-MOD definition site. Keep it under 200 lines by keeping GO-MOD rows tight; route the gate config to gates.md and release engineering to release.md."
  }
 ],
 "standalone": [
  {
   "kind": "skill",
   "path": "/home/mherwig/dev/grimoire-lore/.agents/worktrees/go/skills/go-release/SKILL.md",
   "sources": [
    "go-release.md",
    "go-modules.md",
    "go-gates.md",
    "go-topic-map.md"
   ],
   "brief": "Write the go-release skill (directory skills/go-release/: SKILL.md plus references/ as needed). It is the procedure the map's Artifact set decision and the authoring notes name for cutting a Go release: tag and version decisions (module tags, /vN, retract on a mistake, gorelease or apidiff for libraries), goreleaser v2 check and snapshot, the double-build reproducibility check, version stamping, raw per-platform assets named for mirror consumers plus checksums, signing and provenance, and verification of the published assets. Frontmatter exactly like skills/jvm-release/SKILL.md (name, description with a Use when clause and a Not for clause, license, metadata summary and keywords). The skill is procedure only; it cites GO-REL and GO-MOD rule IDs and never redefines them; any MUST row it duplicates lives in a | # | Finding | Rule | table with the ID last. Mark pinned defaults (owner decisions in go-frame.md) as pinned. Every command in it follows the verification-command shape rules and names the tool version."
  },
  {
   "kind": "skill",
   "path": "/home/mherwig/dev/grimoire-lore/.agents/worktrees/go/skills/go-upgrade/SKILL.md",
   "sources": [
    "go-language.md",
    "go-modules.md",
    "go-gates.md",
    "go-topic-map.md"
   ],
   "brief": "Write the go-upgrade skill (directory skills/go-upgrade/: SKILL.md plus references/ as needed). It is the procedure for moving a module to a new Go release or triaging a dependency: read the release notes and the GODEBUG diff, bump the go and toolchain lines per the policy, run go fix and review its diff, stdversion, bump the golangci-lint pin and config, audit GOEXPERIMENT pins, govulncheck reachability triage (text-mode exit code), replace superseded modules, and re-run the gate. Frontmatter exactly like skills/jvm-release/SKILL.md. Procedure only; cites GO-LANG, GO-MOD and GO-GATE IDs, never redefines them; duplicated MUST rows go in a | # | Finding | Rule | table with the ID last. Every command follows the verification-command shape rules and names the tool version."
  },
  {
   "kind": "skill",
   "path": "/home/mherwig/dev/grimoire-lore/.agents/worktrees/go/skills/go-diagnose/SKILL.md",
   "sources": [
    "go-observability.md",
    "go-concurrency.md",
    "go-io.md",
    "go-testing.md"
   ],
   "brief": "Write the go-diagnose skill (directory skills/go-diagnose/: SKILL.md plus references/ as needed). It is the symptom-routed runbook for a hung, leaking, racy or slow Go process: goroutine dumps (SIGQUIT, GOTRACEBACK), the goroutine leak profile where the release has it, pprof (CPU, heap, allocs, block, mutex), the execution tracer and flight recorder, -race reproduction, GODEBUG knobs, and benchmark evidence with benchstat before any performance claim. Route by symptom like skills/bazel-diagnose/SKILL.md does. Frontmatter exactly like skills/jvm-release/SKILL.md. Procedure only; cites GO-OBS, GO-CONC, GO-IO and GO-TEST IDs, never redefines them. Every command follows the verification-command shape rules and names the Go version."
  },
  {
   "kind": "bazel",
   "path": "/home/mherwig/dev/grimoire-lore/.agents/worktrees/go/rules/bazel-quality/go.md",
   "sources": [
    "go-bazel.md",
    "/home/mherwig/dev/grimoire-lore/.agents/worktrees/go/rules/bazel-quality.md",
    "/home/mherwig/dev/grimoire-lore/.agents/worktrees/go/rules/bazel-quality/java.md"
   ],
   "brief": "Write rules/bazel-quality/go.md, the BZL-GO depth file of the published bazel-quality rule, in the exact shape of rules/bazel-quality/java.md (read it and rules/bazel-quality.md in full first): frontmatter, a scope paragraph stating what BZL-GO owns and which BZL families it cites without restating (BZL-MOD, BZL-HERM, BZL-CACHE, BZL-TEST, BZL-FLAG, BZL-ARCH, BZL-LARK, BZL-CI), a measurement disclosure like java.md's, framed 'if you adopt Bazel for Go', rule tables from go-bazel.md with IDs verbatim, and What Agents Get Wrong Here. Under 250 lines. THEN edit rules/bazel-quality.md minimally: add one routing row to its 'Where the Depth Is' table ('Writing a go_* target, running Gazelle for Go, repinning go_deps, or wiring nogo' -> bazel-quality/go.md), add rules_go, gazelle, go_deps and nogo to its keywords, and name go-quality and go-modules in its Siblings section. Change nothing else in bazel-quality.md. Run the checker on rules/bazel-quality.md (which covers its support directory)."
  }
 ]
}
const NOTES_ANCHOR = 'Authoring notes (binding on the drafters)'
const RUN = '/home/mherwig/.cache/research-lang/go-tools/run.sh'
const FIX = '/home/mherwig/.cache/research-lang/go-tools/fixtures'

const CONTEXT = `PROJECT CONTEXT (context for you, not content to reproduce):
- You are a drafter in phase 7 (Author) of the research-lang program for Go and its ecosystem, run from ${ROOT} (a git worktree — treat it as the repository root; never cd to /home/mherwig/dev/grimoire-lore). The artifacts you write are published through the lore catalog and loaded by coding agents without a human in the loop. Merging to main publishes; you write files, you never commit.
- BINDING INPUTS, read in this order before writing a line: (1) ${ROOT}/.claude/skills/research-lang/references/rule-distillation.md in full — selection, placement, index+support shape, rule anatomy, severity, writing for an agent reader, portability; (2) ${RESEARCH}/go-topic-map.md section "## ${NOTES_ANCHOR}" in full, plus every "Cross-consolidation contradictions" list in the "Wave N landed" sections — these are decisions already taken; you apply them, you do not re-take them; (3) the house exemplars: ${ROOT}/rules/java-quality.md (an index) and ${ROOT}/rules/java-quality/concurrency.md (a depth file) — match their structure, register and density, not their content; (4) the consolidation(s) named in your brief, in full.
- The checker every file must pass: python3 ${ROOT}/.claude/skills/research-lang/scripts/check-artifacts.py <path>. Run it on your own output before returning and fix every finding. Verification-cell shape rules it enforces: give grep a directory operand ('.' at minimum) and -r, never a bare shell glob like .github/workflows/*.yml; one -e per alternative, never an escaped or bare pipe alternation inside a pattern; quote every --include glob (--include='*.go'); never an unquoted '**'; no angle-bracket placeholder inside a quoted pattern — bind it first (NAME=example; grep -rn -e "$NAME" .); never feed operands from $(...); pipe into xargs -r; never put an unescaped pipe character inside a markdown table cell (a shell pipe inside backticks in a cell splits the row: write it as \\| or restructure the command); every table row whose first cell is a rule ID is a rule definition, so a duplicate MUST list in a skill uses | # | Finding | Rule | with the ID last. State in every verification cell whether empty output is the pass or the finding.
- VERIFICATION HONESTY: a verification the consolidation records as watched-red may be copied. A NEW or REWORDED command you write must be run: build a planted violation and a compliant twin under ${FIX}/author-<your-file-stem>/ and run it with ${RUN} (Go 1.27.1, staticcheck, golangci-lint v2.14.0, govulncheck, gofumpt, goimports, deadcode, modernize). A command you could not watch go red is written as a named reading heuristic instead, never as a command.
- Formatting constraints: this repo runs ruff format --check over markdown, so a fenced python block must be ruff-stable; Go snippets are fenced go and must be gofmt-clean (run '${RUN} gofmt -l' on a scratch copy if unsure); YAML fenced yaml; Starlark fenced starlark. Every version-specific row names the Go or tool version and the date verified (${DATE} unless the consolidation dates it). No em dashes in prose; no semicolons in prose. Files over 100 lines carry a Contents line. Depth files never link to other depth files; they cite sibling families by ID and say which file owns them.
- Portability: the artifacts ship to strangers. No fleet paths, no /home paths, no OCX-internal hostnames, no .agents/research links, no repo@sha citations in the shipped text (those live in the corpus); a public exemplar may be named ("kubernetes enables ...") only when the fact is load-bearing. OCX-specific commitments (the SDK wrapping the ocx CLI, the fleet exit table) are written as pinned defaults an adopter overrides once, and marked pinned.
- Budget: an index under 200 lines; a depth file under 300 lines and usually 150 to 250; a SKILL.md under 500 lines with references/ for depth. Rules that fail the four selection tests (agent gets it wrong unaided, checkable, changes a diff, no contradiction) are dropped, and the drop is recorded in your receipt with the ID, not silently.
- Use read-only tools everywhere except your own OUTPUT FILE(S) and your fixture directory. Do not edit a consolidation. Do not edit another drafter's file.
`

const DEPTH_SCHEMA = {
  type: 'object', additionalProperties: false,
  required: ['path', 'lines', 'rule_ids_shipped', 'rule_ids_dropped', 'checker_clean', 'hoist_to_index', 'routing_row', 'commands_run'],
  properties: {
    path: { type: 'string' }, lines: { type: 'number' },
    rule_ids_shipped: { type: 'array', items: { type: 'string' } },
    rule_ids_dropped: { type: 'array', items: { type: 'string' }, description: 'ID: reason' },
    checker_clean: { type: 'boolean' },
    hoist_to_index: { type: 'array', items: { type: 'string' }, description: 'the 1-3 MUST rows from this file that belong in the index non-negotiables, as "ID: one-line rule"' },
    routing_row: { type: 'string', description: 'the task-worded "Doing..." phrase for the index routing table' },
    commands_run: { type: 'number', description: 'new or reworded verification commands watched red on a planted fixture' },
  },
}

const INDEX_SCHEMA = {
  type: 'object', additionalProperties: false,
  required: ['path', 'lines', 'non_negotiables', 'core_rule_ids', 'checker_clean', 'globs'],
  properties: {
    path: { type: 'string' }, lines: { type: 'number' },
    non_negotiables: { type: 'number' }, core_rule_ids: { type: 'array', items: { type: 'string' } },
    checker_clean: { type: 'boolean' }, globs: { type: 'array', items: { type: 'string' } },
  },
}

const STANDALONE_SCHEMA = {
  type: 'object', additionalProperties: false,
  required: ['paths', 'checker_clean', 'notes'],
  properties: { paths: { type: 'array', items: { type: 'string' } }, checker_clean: { type: 'boolean' }, notes: { type: 'array', items: { type: 'string' } } },
}

function depth(rule, d) {
  const out = ROOT + '/rules/' + rule.rule + '/' + d.file
  return agent(`Model rationale: opus — text that becomes an enforced rule; a wrong MUST propagates into every future diff.

${CONTEXT}

YOUR FILE: ${out}  (depth file of the ${rule.rule} rule; ID family ${d.family}; loads when the index routes here for: ${d.task_hint})
SOURCES (read in full): ${d.sources.map(s => RESEARCH + '/' + s).join(', ')}
${d.extra ? '\nADDITIONAL INSTRUCTIONS:\n' + d.extra + '\n' : ''}
Write the depth file: frontmatter (title, summary naming the family and what it owns), a one-paragraph scope stating what the family owns and which sibling families own the neighbours (by family name, never by file link), a Contents line, a "Dates and Floors" block naming the Go and tool versions the rows assume, then sections grouped by the check that catches them — each section opens with the gate command(s) stated once and a rule table (| ID | Rule | Rationale | Verification | Severity |) whose rows keep their consolidation IDs verbatim, followed by at most one minimal wrong/right Go snippet pair per section where the mistake is easier shown than told, then "## What Agents Get Wrong Here" ranked from the consolidation's failure modes. Apply the authoring notes: drop the IDs they name, keep the pinned defaults they set, mark pinned rows, cite the version floors. Where two consolidations conflict, the "Cross-consolidation contradictions" resolution wins. Then run the checker on your file, fix, and return the receipt (hoist_to_index names the 1-3 rows the index must carry as non-negotiables).`,
    { label: 'depth:' + rule.rule + '/' + d.file, phase: 'Depth', model: 'opus', effort: 'high', schema: DEPTH_SCHEMA })
}

function index(rule, depthReceipts) {
  const out = ROOT + '/rules/' + rule.rule + '.md'
  const ok = depthReceipts.filter(Boolean)
  return agent(`Model rationale: opus — the index is the always-loaded surface; every line is paid for in every session.

${CONTEXT}

YOUR FILE: ${out}  (the index of the ${rule.rule} rule)
GLOBS (decided by the map and the authoring notes; copy exactly into frontmatter paths): ${JSON.stringify(rule.glob_list)}
DEPTH FILES already written by sibling drafters (read each in full): ${ok.map(r => r.path).join(', ')}
Their receipts (hoist candidates and routing phrases): ${JSON.stringify(ok.map(r => ({ path: r.path, hoist: r.hoist_to_index, routing: r.routing_row })))}
CONSOLIDATIONS for the index-owned ${rule.core_family} family and the gate: ${rule.index_sources.map(s => RESEARCH + '/' + s).join(', ')}
${rule.extra ? '\nADDITIONAL INSTRUCTIONS:\n' + rule.extra + '\n' : ''}
Write the index in the exact shape of ${ROOT}/rules/java-quality.md: frontmatter (paths = the globs above, summary, keywords, license Apache-2.0, repository https://github.com/ocx-sh/grimoire-lore), a two-line stance, Contents, "## The Gate" (the exact commands, narrowest first, pinned tool versions, chained into one named target), "## Non-Negotiables" (a numbered table of 12-18 merge-blocking rows, each citing depth IDs; hoist from the receipts, then prune to what must be true in every edit), "## Rules This File Owns" (the ${rule.core_family} rows: the never-weaken-the-check rule, the watched-go-red rule, the empty-output rule, read-the-go-line-first, generated-code handling, plus anything the notes assign to the index), "## Where the Depth Is" (one task-worded row per depth file, routed by what the reader is doing, plus the sibling-set rows the notes name), "## Severity", "## Siblings". Under 200 lines. Every depth ID cited must exist in a depth file (grep them). Run the checker on the rule file with its support directory, fix, return the receipt.`,
    { label: 'index:' + rule.rule, phase: 'Index', model: 'opus', effort: 'high', schema: INDEX_SCHEMA })
}

function standalone(item) {
  return agent(`Model rationale: opus — ${item.kind === 'skill' ? 'a procedure agents run unattended; its steps and its refusal conditions are decisions' : 'a depth file added to a published sibling set; it must match that set\'s contract exactly'}.

${CONTEXT}

YOUR OUTPUT: ${item.path}
SOURCES (read in full): ${item.sources.map(s => s.startsWith('/') ? s : RESEARCH + '/' + s).join(', ')}

${item.brief}

Run the checker on your output, fix, return the receipt.`,
    { label: item.kind + ':' + item.path.split('/').slice(-2).join('/'), phase: 'Standalone', model: 'opus', effort: 'high', schema: STANDALONE_SCHEMA })
}

// ---------------------------------------------------------------- Run
const nDepth = PLAN.rules.reduce((n, r) => n + r.depth.length, 0)
log('Authoring: ' + PLAN.rules.length + ' rules, ' + nDepth + ' depth files, ' + PLAN.standalone.length + ' standalone')

const ruleResults = pipeline(
  PLAN.rules,
  rule => parallel(rule.depth.map(d => () => depth(rule, d))),
  (receipts, rule) => {
    const ok = receipts.filter(Boolean)
    if (ok.length < rule.depth.length) log(rule.rule + ': ' + (rule.depth.length - ok.length) + ' depth drafter(s) dropped; index proceeds with ' + ok.length)
    if (!ok.length) return { rule: rule.rule, depth: receipts, index: null }
    return index(rule, ok).then(ix => ({ rule: rule.rule, depth: receipts, index: ix }))
  },
)
const standaloneResults = parallel(PLAN.standalone.map(item => () => standalone(item)))
const [rules, standaloneOut] = await Promise.all([ruleResults, standaloneResults])

const dropped = rules.filter(Boolean).flatMap(r => (r.depth || []).filter(Boolean).flatMap(d => d.rule_ids_dropped || []))
const unclean = [
  ...rules.filter(Boolean).flatMap(r => (r.depth || []).filter(Boolean).filter(d => !d.checker_clean).map(d => d.path)),
  ...rules.filter(Boolean).filter(r => r.index && !r.index.checker_clean).map(r => r.index.path),
  ...standaloneOut.filter(Boolean).filter(s => !s.checker_clean).flatMap(s => s.paths),
]
log('Done: ' + rules.filter(r => r && r.index).length + '/' + PLAN.rules.length + ' indexes · ' + dropped.length + ' IDs dropped at authoring · ' + unclean.length + ' files still unclean')
return { rules, standalone: standaloneOut, dropped_ids: dropped, unclean }
